# Generated by /feature-spec
# Feature: Mode B Feature & Mode C Review-Fix (FEAT-FORGE-008)
# Stack: python
# Assumptions: 17 (see mode-b-feature-and-mode-c-review-fix_assumptions.yaml)
# Generated: 2026-04-27T00:00:00Z

@feat-forge-008 @mode-b-feature @mode-c-review-fix
Feature: Mode B Feature & Mode C Review-Fix
  As Rich, the operator triggering a non-greenfield build
  I want Forge to drive (Mode B) a single new feature on an existing project
    from /feature-spec through autobuild to a pull-request review, or
    (Mode C) a review-fix loop on an existing subject through /task-review
    and /task-work in a single supervised run
  So that I can land a reviewed pull request — or a clean review pass —
    without re-running the upfront delegation and architecture stages each time

  Background:
    Given Forge is registered on the fleet
    And the project repository already contains an architecture and design baseline
    And a writable worktree allowlist is configured for the project
    And the operator's calibration history has been ingested
    And a build has been queued for a feature identifier with a non-greenfield mode

  # ===========================================================================
  # GROUP A — Key Examples
  # ===========================================================================

  # Why: Mode B's capstone happy path — no PO/architect/system-arch/system-design upfront; start at /feature-spec
  # [ASSUMPTION: confidence=high] Mode B chain is /feature-spec → /feature-plan → autobuild → pull-request review (skipping product-owner, architect, /system-arch, and /system-design)
  @mode-b @key-example @smoke
  Scenario: A Mode B build drives a single new feature from specification to pull-request review
    Given the build is picked up from the queue in feature mode
    When Forge invokes feature specification, feature planning, and autobuild in order for that feature
    And every gated stage along the way is auto-approved
    And the pull request is created on the working branch
    Then the build should pause at pull-request review for mandatory human approval
    And no product-owner, architect, architecture, or design dispatch should have been recorded
    And the recorded stage history should contain feature specification, feature planning, autobuild, and pull-request review in order

  # Why: Mode B forward propagation — the spec output drives the plan, the plan drives autobuild
  @mode-b @key-example
  Scenario: The approved feature specification is supplied as input to feature planning and the approved plan is supplied to autobuild
    Given the feature specification stage has produced approved spec artefacts
    When Forge invokes feature planning
    Then the planning dispatch should be supplied with the spec artefact paths as context
    And feature planning should not be invoked before the specification is recorded as approved
    And once planning is approved, autobuild should be supplied with the plan artefact paths as context

  # Why: Mode B autobuild uses the inherited async-subagent pattern so the supervisor stays responsive
  # [ASSUMPTION: confidence=high] Mode B autobuild dispatch reuses the AsyncSubAgent pattern with the async_tasks state channel exposing wave and task indices (inherited from FEAT-FORGE-007)
  @mode-b @key-example @smoke
  Scenario: Mode B autobuild runs as an asynchronous subagent so the supervisor remains responsive during the run
    Given the feature has an approved build plan
    When Forge dispatches autobuild for that feature
    Then the dispatch should be a long-running asynchronous task with its own task identifier
    And the live status view should report wave and task progress for the running autobuild
    And the supervisor should remain available to answer status queries while the autobuild is in flight

  # Why: PR review is constitutionally pinned in Mode B, just as in Mode A — never auto-approve
  # [ASSUMPTION: confidence=high] Pull-request review is constitutionally pinned to mandatory human approval in every mode, enforced both at the prompt and the executor layer (belt-and-braces)
  @mode-b @key-example @regression
  Scenario: A Mode B pull-request review is mandatory human approval regardless of upstream Coach scores
    Given every preceding Mode B stage has been auto-approved with high Coach scores
    When Forge reaches the pull-request review stage
    Then the build should pause for mandatory human approval
    And the pause should not be eligible to be auto-approved

  # Why: A flag-for-review at any non-constitutional Mode B stage suspends the build and the next stage waits
  @mode-b @key-example
  Scenario: A flagged-for-review checkpoint in Mode B pauses the build and the next stage waits on the response
    Given Mode B is in the feature-planning stage and that stage has been flagged for review
    When the operator responds with approve
    Then the build should resume from autobuild
    And the prior approved spec and plan artefacts should still be available as context
    And no autobuild dispatch should have been recorded before the response was received

  # Why: Successful Mode B build records a session outcome with the chain of gate decisions for the inherited stages only
  @mode-b @key-example
  Scenario: Completing the Mode B pull-request review writes a session outcome that links every gate decision in order
    Given a Mode B build is paused at pull-request review
    When the operator approves the pull request
    Then the build should reach a complete terminal state
    And the recorded session outcome should reference every gate decision from feature specification through pull-request review
    And the recorded gate decisions should be linked in chronological order

  # Why: Mode C's capstone happy path — review identifies fix tasks; work cycles through them under gating
  # [ASSUMPTION: confidence=high] Mode C chain is /task-review → /task-work × N (one /task-work dispatch per fix task identified by /task-review), with optional pull-request review at the end if changes are pushed
  @mode-c @key-example @smoke
  Scenario: A Mode C build runs the review-fix cycle from an initial review through one work dispatch per identified fix task
    Given the build is picked up from the queue in review-fix mode
    When Forge invokes the task-review stage and it returns a non-empty set of fix tasks
    And every fix task is auto-approved at its gate
    And Forge dispatches a task-work invocation for each fix task in turn
    Then exactly one task-work dispatch should be recorded per fix task identified
    And no task-work dispatch should occur before its corresponding fix task is approved

  # Why: Mode C forward propagation — the /task-review output supplies fix-task definitions to /task-work
  @mode-c @key-example
  Scenario: Each /task-work dispatch is supplied with the fix-task definition produced by /task-review
    Given the task-review stage has produced fix-task definitions
    When Forge dispatches task-work for a given fix task
    Then the task-work dispatch context should include the fix-task definition produced by task-review
    And no task-work dispatch should be issued for a fix task before its review entry is recorded as approved

  # Why: Mode C may produce a pull request once fixes are applied — the constitutional rule still pins review to a human
  # [ASSUMPTION: confidence=medium] Mode C may culminate in a pull-request review when fixes change the working branch; the constitutional pull-request rule applies in Mode C exactly as in Modes A and B
  @mode-c @key-example @regression
  Scenario: A Mode C build that produces changes ends with a pull-request review pinned to mandatory human approval
    Given a Mode C build has applied changes through one or more task-work dispatches
    When Forge reaches the pull-request review stage
    Then the build should pause for mandatory human approval
    And the pause should not be eligible to be auto-approved

  # ===========================================================================
  # GROUP B — Boundary Conditions
  # ===========================================================================

  # Why: Single-feature Mode B is the only valid scope shape — there is no system-design catalogue iteration
  # [ASSUMPTION: confidence=high] Mode B operates on exactly one feature per build; multi-feature catalogues belong to Mode A only
  @mode-b @boundary @smoke
  Scenario: A Mode B build operates on exactly one feature and culminates in exactly one pull-request review pause
    Given a Mode B build is queued for a single feature identifier
    When the build progresses through every Mode B stage with auto-approval at every flagged-for-review checkpoint
    Then exactly one feature-specification dispatch and one feature-planning dispatch and one autobuild dispatch should be recorded
    And the chain should culminate in a single pull-request review pause

  # Why: Stage-ordering invariant for Mode B — every downstream stage waits on its prerequisite
  @mode-b @boundary
  Scenario Outline: A downstream Mode B stage is not dispatched before its prerequisite has reached the approved state
    Given the prerequisite "<prerequisite>" has not yet been approved
    When the build's reasoning loop considers the next dispatch
    Then no dispatch should be issued for "<stage>"

    Examples:
      | stage         | prerequisite                 |
      | feature-plan  | feature-spec for the feature |
      | autobuild     | feature-plan for the feature |
      | pull-request  | autobuild for the feature    |

  # Why: Just-outside boundary — Mode B with no spec output cannot proceed to planning
  @mode-b @boundary @negative
  Scenario: A Mode B feature-specification stage that produces no spec artefacts cannot enter feature planning
    Given the feature-specification stage has produced no spec artefacts
    When the next-stage decision is reached
    Then the build should not issue a feature-planning dispatch
    And the build should be flagged for review with the missing-spec rationale recorded

  # Why: Just-inside boundary — Mode C with zero fix tasks completes without dispatching task-work
  # [ASSUMPTION: confidence=high] If /task-review returns an empty set of fix tasks, the Mode C build completes without dispatching /task-work and records the clean-review outcome
  @mode-c @boundary
  Scenario: A Mode C task-review that returns no fix tasks completes the build without dispatching any task-work
    Given the task-review stage has returned an empty set of fix tasks
    When the build evaluates the review outcome
    Then no task-work dispatch should be issued
    And the build should reach a complete terminal state with a clean-review outcome recorded

  # Why: Mode C scales with the number of identified fix tasks — exercises the iteration boundary
  @mode-c @boundary
  Scenario Outline: Mode C dispatches one /task-work per fix task identified by /task-review
    Given the task-review stage has returned <count> fix tasks
    When the build progresses through the fix-task loop
    Then <count> task-work dispatches should be recorded
    And every dispatched task-work should reference exactly one fix task identifier

    Examples:
      | count |
      | 1     |
      | 3     |
      | 5     |

  # Why: Stage-ordering invariant for Mode C — task-work waits on its review entry's approval
  @mode-c @boundary
  Scenario Outline: A Mode C downstream stage is not dispatched before its prerequisite has reached the approved state
    Given the prerequisite "<prerequisite>" has not yet been approved
    When the build's reasoning loop considers the next dispatch
    Then no dispatch should be issued for "<stage>"

    Examples:
      | stage        | prerequisite                       |
      | task-work    | task-review entry for the fix task |
      | pull-request | task-work for every fix task       |

  # ===========================================================================
  # GROUP C — Negative Cases
  # ===========================================================================

  # Why: A hard-stop at the first stage of Mode B terminates the build; no later dispatch should occur
  @mode-b @negative
  Scenario: A hard-stop at the Mode B feature-specification stage prevents any later stage from being dispatched
    Given the feature-specification stage returns a result that causes a hard-stop gate
    When the build evaluates the result
    Then the build should reach a failed terminal state
    And no feature-planning, autobuild, or pull-request dispatch should have been recorded

  # Why: A failed feature-spec dispatch must not cascade into a planning attempt
  @mode-b @negative
  Scenario: A failed Mode B feature-specification dispatch halts the build before planning
    Given the build is in the feature-specification stage
    When the feature-specification dispatch returns a failed result
    Then the build should not issue a feature-planning dispatch
    And the build should not issue an autobuild dispatch
    And the failed-spec rationale should be recorded against the build

  # Why: Constitutional override — Mode B PR review can never be auto-approved by upstream score alone
  @mode-b @negative @regression
  Scenario: Auto-approval is refused at the Mode B pull-request review stage even when the upstream Coach score is at the maximum
    Given the upstream Mode B stages have all returned the maximum Coach score
    When the build reaches the pull-request review stage
    Then the build should pause for mandatory human approval
    And the pause should not be eligible to resolve without a human decision

  # Why: Skip steering must not bypass the constitutional PR-review gate in Mode B
  @mode-b @negative @regression
  Scenario: A skip directive issued against the Mode B pull-request review stage is refused
    Given the Mode B build is paused at pull-request review
    When the operator issues a skip directive for that stage
    Then the build should remain paused for mandatory human approval
    And the skip should be recorded as refused with a constitutional rationale

  # Why: Mode B autobuild internal hard-stop must surface to the build and prevent PR creation
  @mode-b @negative
  Scenario: A Mode B autobuild internal hard-stop is propagated to the build and prevents pull-request creation
    Given Mode B autobuild is in flight
    When an internal task hits a hard-stop gate
    Then the autobuild lifecycle should reach a failed terminal state
    And no pull-request creation dispatch should be issued
    And the build's stage history should record the autobuild failure with the hard-stop rationale

  # Why: Reject decision at any pre-PR pause is terminal — there is no implicit retry
  @mode-b @mode-c @negative
  Scenario: A reject decision at a flagged-for-review checkpoint before pull-request review terminates the build
    Given the build is paused at any flagged-for-review checkpoint before pull-request review
    When the operator responds with reject
    Then the build should reach a failed terminal state
    And no later stage should be dispatched

  # Why: A hard-stop at the Mode C task-review stage terminates the build; no fix work should run
  @mode-c @negative
  Scenario: A hard-stop at the Mode C task-review stage prevents any task-work from being dispatched
    Given the task-review stage returns a result that causes a hard-stop gate
    When the build evaluates the review outcome
    Then the build should reach a failed terminal state
    And no task-work dispatch should have been recorded

  # Why: A failed /task-work for a fix task is recorded and prevents that fix task from being marked as completed
  # [ASSUMPTION: confidence=medium] A failed /task-work for a fix task halts that fix task's progression but does not implicitly cancel later fix tasks; the build's continuation is decided at the gate
  @mode-c @negative
  Scenario: A failed Mode C task-work dispatch records the failure against its fix task and blocks pull-request creation when no fix task has succeeded
    Given a Mode C fix task is in flight under task-work
    When the task-work dispatch returns a failed result
    Then the failure should be recorded against that fix task on the build's stage history
    And no pull-request creation dispatch should be issued for that fix task

  # ===========================================================================
  # GROUP D — Edge Cases
  # ===========================================================================

  # Why: Crash mid-stage triggers anchor §5 retry-from-scratch in Mode B as in Mode A
  @mode-b @edge-case
  Scenario Outline: A crash during any non-terminal Mode B stage is recovered by retry-from-scratch
    Given the Mode B build is in the "<stage>" stage
    When the runtime restarts after an unexpected interruption
    Then the build should re-enter the preparing state
    And the prior in-flight stage should be reattempted from the start

    Examples:
      | stage        |
      | feature-spec |
      | feature-plan |
      | autobuild    |

  # Why: Crash mid-stage triggers retry-from-scratch in Mode C as well
  @mode-c @edge-case
  Scenario Outline: A crash during any non-terminal Mode C stage is recovered by retry-from-scratch
    Given the Mode C build is in the "<stage>" stage
    When the runtime restarts after an unexpected interruption
    Then the build should re-enter the preparing state
    And the prior in-flight stage should be reattempted from the start

    Examples:
      | stage       |
      | task-review |
      | task-work   |

  # Why: Async subagent state channel is advisory on recovery — durable history is authoritative
  # [ASSUMPTION: confidence=high] On crash recovery during Mode B autobuild or Mode C task-work, durable history is authoritative and any live async-subagent state channel is advisory (inherited from FEAT-FORGE-007)
  @mode-b @mode-c @edge-case
  Scenario: After a crash during an asynchronous Mode B autobuild or Mode C task-work, durable history is the authoritative status source
    Given an asynchronous stage was in flight when the runtime crashed
    When the runtime restarts
    Then the build's authoritative status should be read from the durable history
    And any live state channel data should be treated as advisory

  # Why: Cancel during a paused stage produces a synthetic reject and terminates the build (CLI cancel mapping)
  @mode-b @mode-c @edge-case
  Scenario: A cancel directive while paused at a Mode B or Mode C checkpoint terminates the build with a synthetic reject
    Given the build is paused at a flagged-for-review checkpoint
    When the operator issues a cancel directive
    Then the pause should resolve as a synthetic reject with a cancel rationale
    And the build should reach a cancelled terminal state

  # Why: Cancel during an asynchronous stage halts the async task and terminates the build
  @mode-b @mode-c @edge-case
  Scenario: A cancel directive during an asynchronous Mode B autobuild or Mode C task-work halts the asynchronous task and terminates the build
    Given an asynchronous stage is in flight
    When the operator issues a cancel directive for the build
    Then the asynchronous task's live state should reach the cancelled lifecycle
    And the build should reach a cancelled terminal state with no pull-request creation attempted

  # Why: Skip on a non-constitutional stage records the skip and continues the chain
  @mode-b @mode-c @edge-case
  Scenario: A skip directive on a non-constitutional stage marks that stage skipped and resumes the chain
    Given the build is paused at a flagged-for-review checkpoint that is not pull-request review
    When the operator issues a skip directive
    Then the stage should be recorded as skipped on the build's stage history
    And the build should resume at the next stage in the chain

  # Why: Approval responses are routed by build identifier — concurrent paused builds remain isolated
  @mode-b @mode-c @edge-case
  Scenario: An approval response is routed to the Mode B or Mode C build whose identifier matches the response channel
    Given two builds are simultaneously paused at flagged-for-review checkpoints
    When an approval response is received that matches one build's identifier
    Then only that build should resume
    And the other paused build should remain awaiting its own approval

  # Why: Repeat approval for the same request is idempotent — first response wins (CLI replay safety)
  @mode-b @mode-c @edge-case
  Scenario: A duplicate approval response for the same paused stage is ignored
    Given the build has resumed after an approval response was honoured
    When a duplicate response with the same request identifier arrives
    Then the build should not re-resume
    And no additional stage transition should be recorded for the duplicate

  # Why: Mode C terminates the cycle when /task-review returns a clean review after a fix iteration
  # [ASSUMPTION: confidence=medium] Mode C terminates the review-fix cycle when a follow-up /task-review returns no further fix tasks; iteration count is bounded by reviewer judgement, not a fixed numeric ceiling
  @mode-c @edge-case
  Scenario: A follow-up Mode C task-review that returns no further fix tasks terminates the review-fix cycle
    Given the Mode C build has completed every dispatched task-work
    When Forge invokes a follow-up task-review
    And the follow-up review returns no further fix tasks
    Then no further task-work dispatch should be issued
    And the build should advance to the next stage in the chain or to a clean terminal outcome

  # ===========================================================================
  # GROUP E — Security
  # ===========================================================================

  # Why: Constitutional pull-request rule is enforced at both the prompt layer and the executor layer in every mode
  # [ASSUMPTION: confidence=high] Constitutional pull-request enforcement is mode-agnostic — the executor-side hardcoded branch fires for any tool resembling pull-request creation or review regardless of mode
  @mode-b @mode-c @security @regression
  Scenario: Mode B and Mode C pull-request review enforcement holds even if a misconfigured prompt would have allowed auto-approve
    Given the system prompt is configured incorrectly so that pull-request review appears auto-approvable
    When the build reaches the pull-request review stage in either mode
    Then the executor layer should still enforce mandatory human approval

  # Why: Subprocess results cannot escalate beyond their delegated authority at the gating layer
  @mode-b @mode-c @security
  Scenario: A subprocess result that asserts an override of constitutional rules is ignored at gating
    Given a subprocess stage returns a result claiming to override the pull-request review rule
    When the build reaches the pull-request review stage
    Then the override claim should be ignored
    And the build should pause for mandatory human approval

  # Why: Each build runs only inside its ephemeral worktree allowlist — no cross-build leakage in either mode
  @mode-b @mode-c @security
  Scenario: Mode B and Mode C subprocess stages run only against the build's ephemeral worktree path
    Given the build has a configured worktree path
    When any subprocess stage is dispatched
    Then the working directory used by the subprocess should fall under the build's worktree allowlist
    And no path outside that allowlist should be writable by the dispatched subprocess

  # ===========================================================================
  # GROUP F — Concurrency
  # ===========================================================================

  # Why: Two concurrent Mode B builds run with isolated approval channels and isolated autobuild task identifiers
  @mode-b @concurrency
  Scenario: Two concurrent Mode B builds use separate approval channels and separate autobuild task identifiers
    Given two distinct Mode B builds are dispatched at approximately the same time
    When both builds reach autobuild and both later reach a flagged-for-review pause
    Then each build should have a distinct autobuild task identifier
    And each build's approval pause should resolve only on a response matching its own build identifier

  # Why: Mode B and Mode C can run concurrently — different stage chains over the same checkpoint substrate
  @mode-b @mode-c @concurrency
  Scenario: A Mode B and a Mode C build run concurrently with isolated approval channels and stage chains
    Given a Mode B build is in flight at autobuild
    And a Mode C build is in flight at task-work
    When each build reaches a flagged-for-review pause
    Then each build's approval pause should resolve only on a response matching its own build identifier
    And the supervisor should be able to dispatch the next stage of either build without waiting on the other

  # Why: A long-running asynchronous stage does not block the supervisor's reasoning loop for unrelated builds
  @mode-b @mode-c @concurrency
  Scenario: The supervisor can dispatch a different build's stage while another build's asynchronous stage is mid-flight
    Given a first build's asynchronous stage is in the running lifecycle
    When a second build is queued and picked up
    Then the second build's first stage should be dispatched without waiting for the first build's asynchronous stage to complete

  # ===========================================================================
  # GROUP G — Data Integrity
  # ===========================================================================

  # Why: Mode B canonical stage-history ordering — the chain reflects the actual order without PO/architect/system-arch/system-design entries
  @mode-b @data-integrity
  Scenario: The recorded stage history of a successful Mode B build follows the canonical Mode B ordering
    Given a Mode B build has reached the complete terminal state
    When the operator inspects the build's stage history
    Then the stage entries should appear in the order feature-specification, feature-planning, autobuild, then pull-request review
    And no product-owner, architect, architecture, or system-design entries should appear

  # Why: Mode C canonical stage-history ordering — review entries precede the corresponding work entries
  @mode-c @data-integrity
  Scenario: The recorded stage history of a successful Mode C build follows the canonical Mode C ordering
    Given a Mode C build has reached the complete terminal state
    When the operator inspects the build's stage history
    Then a task-review entry should precede every task-work entry it produced
    And task-work entries for distinct fix tasks should each reference the fix task identifier they implemented

  # Why: Per-fix-task artefact attribution — Mode C work products belong to the fix task that produced them
  @mode-c @data-integrity
  Scenario: Per-fix-task artefact paths are recorded against the fix task that produced them
    Given the task-review stage has produced two or more fix tasks
    When task-work completes for each fix task
    Then each task-work stage entry should record the artefact paths produced for its fix task only
    And no artefact path should be attributed to more than one fix task

  # Why: A failed outbound notification publish must not regress an authoritative durable approval
  @mode-b @mode-c @data-integrity
  Scenario: A notification publish failure does not regress a Mode B or Mode C build's recorded stage progress
    Given a stage has been approved
    When the outbound notification publish for that approval fails
    Then the stage should still be recorded as approved on the build's history
    And the next stage's prerequisite should still evaluate as satisfied

  # ===========================================================================
  # GROUP H — Integration Boundaries
  # ===========================================================================

  # Why: End-to-end smoke for Mode B — minimal queue → PR-awaiting-review
  @mode-b @integration @smoke
  Scenario: A minimal Mode B build for a single feature drives to a pull request awaiting human review
    Given the operator queues a Mode B build for a single feature identifier
    When the build proceeds through every Mode B stage with auto-approval at every flagged-for-review checkpoint
    Then the terminal state should be paused at pull-request review awaiting human approval
    And a pull-request URL should be recorded against the build

  # Why: End-to-end smoke for Mode C — minimal queue → clean-review terminal
  @mode-c @integration @smoke
  Scenario: A minimal Mode C build with a single fix task completes through one task-review and one task-work dispatch
    Given the operator queues a Mode C build
    And the initial task-review will return exactly one fix task
    When the build proceeds with auto-approval at every flagged-for-review checkpoint
    Then exactly one task-review and one task-work stage entry should be recorded
    And the build should reach a complete or pull-request-review terminal outcome consistent with the changes applied

  # Why: An internal asynchronous pause must be observable through the supervisor without blocking other supervisor work
  @mode-b @mode-c @integration
  Scenario: An internal asynchronous-stage pause is observable through the supervisor without blocking other supervisor work
    Given an asynchronous stage's internal task fires a flagged-for-review pause
    When the operator queries live status
    Then the asynchronous stage's live state should report awaiting-approval with the stage label
    And the supervisor should remain free to perform other work for other builds

  # Why: Mode B/C inherit the correlation-threading audit anchor — every lifecycle event for one build carries one correlation id
  @mode-b @mode-c @integration @data-integrity
  Scenario: Every published lifecycle event for a Mode B or Mode C build threads the same correlation identifier from queue to terminal
    Given the build has been queued with a correlation identifier
    When the build progresses to a terminal state
    Then every lifecycle event published for that build should carry that same correlation identifier

  # ===========================================================================
  # GROUP I — Expansion (additional integration-level scenarios)
  # ===========================================================================

  # Why: First-write-wins discipline survives at the integration level even when two operators respond simultaneously
  @mode-b @mode-c @concurrency @edge-case
  Scenario: Two simultaneous approval responses for the same paused build resolve as first-wins
    Given the build is paused at a flagged-for-review checkpoint
    When two approval responses arrive simultaneously for the same paused stage with different decisions
    Then the build should resolve under exactly one of those decisions
    And no second resume should be applied for the duplicate response

  # Why: Calibration snapshot stability — a long-running build sees a consistent priors view, not a moving target
  # [ASSUMPTION: confidence=medium] Calibration priors are snapshotted at build start and remain stable for the duration of that build (inherited from FEAT-FORGE-007)
  @mode-b @mode-c @data-integrity
  Scenario: Calibration priors captured at the start of a Mode B or Mode C build remain the snapshot used by every stage of that build
    Given a build is picked up and a calibration-priors snapshot is captured at start
    When the operator's calibration history is updated while the build is mid-run
    Then later stages of the in-flight build should still use the priors snapshot captured at start

  # Why: Long-term memory seeding is best-effort and must never regress an authoritative approval in either mode
  @mode-b @mode-c @integration @data-integrity
  Scenario: A long-term-memory seeding failure for one stage does not regress that stage's recorded approval
    Given a stage has been approved by gating
    When the long-term-memory seeding for that stage's gate decision fails
    Then the stage should still be recorded as approved on the build's history
    And the next stage's prerequisite should still evaluate as satisfied

  # ===========================================================================
  # GROUP J — Security expansion
  # ===========================================================================

  # Why: Mode B's stage chain is bounded — a misconfigured manifest cannot trick the supervisor into running upstream Mode A stages
  # [ASSUMPTION: confidence=medium] The supervisor's mode-aware planning refuses to dispatch /system-arch or /system-design in Mode B even if a context manifest references those stages
  @mode-b @security
  Scenario: A Mode B build refuses to dispatch /system-arch or /system-design even when a context manifest references those stages
    Given a Mode B build is queued
    And the project's context manifest references /system-arch and /system-design as available stages
    When the build's reasoning loop plans the stage chain
    Then no /system-arch or /system-design dispatch should be issued
    And the recorded stage history should contain only Mode B stages

  # ===========================================================================
  # GROUP K — Concurrency expansion
  # ===========================================================================

  # Why: Three-way mode interleave — proves the substrate isolates approval channels and stage chains across all modes
  @mode-b @mode-c @concurrency
  Scenario: Three concurrent builds — one Mode A, one Mode B, one Mode C — hold isolated approval channels and isolated stage chains
    Given a Mode A build, a Mode B build, and a Mode C build are dispatched at approximately the same time
    When each build reaches a flagged-for-review pause on its own chain
    Then each build's approval pause should resolve only on a response matching its own build identifier
    And each build's recorded stage history should reflect only the stages of its own mode

  # ===========================================================================
  # GROUP L — Data Integrity expansion
  # ===========================================================================

  # Why: Positive assertion that Mode B never dispatches to specialists — there is no degraded rationale to record because there is no specialist stage
  # [ASSUMPTION: confidence=high] Mode B does not dispatch to product-owner or architect specialists, so specialist-availability outages do not gate or pause a Mode B build
  @mode-b @data-integrity
  Scenario: A Mode B build does not record a degraded-specialist rationale because no specialist dispatch is attempted
    Given no product-owner or architect specialist is reachable on the fleet
    When a Mode B build is queued and picked up
    Then no specialist dispatch should be attempted
    And no degraded-specialist rationale should appear on the build's stage history
    And the build should proceed into the feature-specification stage

  # Why: Mode C's fix-task lineage is the audit anchor for review-fix — every work entry traces back to its originating review
  @mode-c @data-integrity
  Scenario: Each Mode C task-work stage entry records the fix-task lineage back to its originating task-review entry
    Given the task-review stage has produced two or more fix tasks
    When task-work completes for each fix task
    Then each task-work stage entry should record the fix-task identifier it implemented
    And each fix-task identifier should reference the task-review stage entry that produced it

  # ===========================================================================
  # GROUP M — Integration Boundaries expansion
  # ===========================================================================

  # Why: A successful autobuild that produces no diff cannot create a pull request — the constitutional rule has nothing to gate, and the build records that as a no-op
  # [ASSUMPTION: confidence=medium] When a Mode B autobuild succeeds without producing a diff against the working branch, no pull-request creation is attempted and the build terminates with a no-op outcome rather than pausing at pull-request review
  @mode-b @integration
  Scenario: A Mode B build whose autobuild produces no diff does not attempt pull-request creation
    Given the Mode B autobuild has reached the completed lifecycle with no changes against the working branch
    When the build evaluates the next stage
    Then no pull-request creation dispatch should be issued
    And the build should reach a terminal state with a no-op rationale recorded
    And no pull-request URL should be recorded against the build

  # ===========================================================================
  # GROUP N — Mode-interaction expansion
  # ===========================================================================

  # Why: Mode boundaries are per-build — a follow-up feature on a previously-built project starts a fresh Mode B build, not a continuation
  # [ASSUMPTION: confidence=high] Each queued build is its own lifecycle; a follow-up feature added after a Mode A run starts a fresh Mode B build with its own build identifier and its own correlation identifier
  @mode-b @edge-case
  Scenario: A follow-up feature added after a prior Mode A build is treated as a fresh Mode B build with its own identifiers
    Given a prior Mode A build for the same project has reached a terminal state
    When the operator queues a follow-up feature on that project
    Then the follow-up should be dispatched as a fresh Mode B build with its own build identifier and correlation identifier
    And the follow-up's stage history should not be appended to the prior Mode A build's stage history

  # Why: A Mode C run that finds nothing to fix and produces no commits has nothing to push — the build closes cleanly without invoking the constitutional gate
  # [ASSUMPTION: confidence=medium] A Mode C run that produces no commits ends in a clean-review terminal outcome with no pull-request creation attempt and no PR URL
  @mode-c @integration
  Scenario: A Mode C build that produces no commits ends in a clean-review terminal outcome with no pull-request creation attempt
    Given a Mode C build has completed every dispatched task-work without producing commits
    When the build evaluates the next stage
    Then no pull-request creation dispatch should be issued
    And the build should reach a complete terminal state with a clean-review outcome recorded
    And no pull-request URL should be recorded against the build
