# Generated by /feature-spec
# Feature: Pipeline State Machine and Configuration (FEAT-FORGE-001)
# Stack: python
# Assumptions: 5 (see pipeline-state-machine-and-configuration_assumptions.yaml)
# Generated: 2026-04-23T20:00:00Z
# Revised:   2026-04-24 — dropped turn-budget ceiling (ASSUM-002 retired); promoted ASSUM-005 to medium

@feat-forge-001 @pipeline-state-machine
Feature: Pipeline State Machine and Configuration
  As Rich, the sole operator of Forge
  I want to enqueue, observe, and steer pipeline builds through a durable state machine
  So that I always have a consistent, crash-safe view of what the pipeline is doing
  and have a reliable way to start, pause, cancel, or skip stages from the command line

  Background:
    Given Forge is configured from the project configuration file

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP A — Key Examples
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Core write path — enqueue a feature for build from the CLI
  @task:TASK-PSM-008
  @key-example @smoke
  Scenario: Queueing a new feature creates a pending build
    Given I have a feature description at a permitted repository path
    When I queue the feature for a build
    Then a new build should be recorded as pending pickup
    And the queue should report a correlation identifier for the request
    And the command should report success

  # Why: Full happy-path lifecycle — the build completes end to end
  @task:TASK-PSM-004
  @key-example @smoke
  Scenario: A queued build progresses through the lifecycle to completion
    Given a build has been queued for a feature
    When the pipeline picks up the build and all stages succeed
    Then the build should transition from pending pickup, to preparation, to running, to finalisation, to complete
    And the build should record the moment preparation began and the moment it completed
    And the build should expose the pull request it produced

  # Why: Core read path — `forge status` surfaces live activity without touching the messaging layer
  @task:TASK-PSM-009
  @key-example @smoke
  Scenario: Viewing status shows all non-terminal builds and recent outcomes
    Given one build is currently running and one build completed yesterday
    When I ask for the current pipeline status
    Then the running build should be shown as active with its current stage
    And the recently completed build should be shown as a recent outcome
    And the status query should not require the pipeline agent to be reachable

  # Why: Core read path — `forge history` summarises prior builds for a feature
  @task:TASK-PSM-010
  @key-example
  Scenario: Viewing history for a specific feature lists all prior attempts
    Given three previous builds exist for the same feature, two complete and one failed
    When I ask for the history of that feature
    Then all three attempts should be listed from most recent to oldest
    And each attempt should display its final outcome and the stages it went through

  # Why: Configuration loading — defaults come from forge.yaml, overridable on the command line
  @task:TASK-PSM-003
  @key-example
  Scenario: Queueing a build applies configuration defaults when no overrides are given
    Given the configuration specifies a default reasoning-turn budget and a default stage timeout
    When I queue a feature without specifying those values
    Then the new build should adopt the configured defaults
    And when I override one of those values on the command line
    Then the new build should record the overridden value instead of the default

  # Why: Single-writer discipline — the read path remains available even while the agent is writing
  @task:TASK-PSM-002
  @key-example
  Scenario: Status and history queries remain responsive while a build is actively writing
    Given a build is actively running and recording stage outcomes
    When I ask for status at the same moment
    Then the status query should return promptly without waiting for the writer

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP B — Boundary Conditions
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Just-inside boundary — the minimum reasoning-turn budget and the configured default are both accepted
  @task:TASK-PSM-003
  @boundary
  Scenario Outline: Reasoning-turn budget overrides at or above the minimum are accepted
    Given the default reasoning-turn budget is five
    When I queue a feature with a reasoning-turn budget of <turns>
    Then the build should be recorded with a reasoning-turn budget of <turns>

    Examples:
      | turns |
      | 1     |
      | 5     |

  # Why: Just-outside boundary — zero or negative turn budgets are nonsensical
  # [ASSUMPTION: confidence=medium] Reasoning-turn budget must be at least 1;
  # a zero-turn budget cannot perform any reasoning work.
  @task:TASK-PSM-003
  @boundary @negative
  Scenario Outline: Reasoning-turn budgets outside the permitted range are rejected
    When I queue a feature with a reasoning-turn budget of <turns>
    Then the queue command should be rejected with a configuration error
    And no new build should be recorded

    Examples:
      | turns |
      | 0     |
      | -1    |

  # Why: History limit default and just-inside bound
  @task:TASK-PSM-010
  @boundary
  Scenario Outline: History returns at most the requested number of entries
    Given <available> prior builds exist
    When I ask for history with a limit of <limit>
    Then at most <expected> entries should be returned in newest-first order

    Examples:
      | available | limit | expected |
      | 10        | 50    | 10       |
      | 60        | 50    | 50       |
      | 60        | 1     | 1        |

  # Why: Just-inside default — `forge history` with no arguments returns the 50 most recent builds
  @task:TASK-PSM-010
  @boundary
  Scenario: History with no arguments returns the 50 most recent builds by default
    Given 75 prior builds exist
    When I ask for history without specifying a limit
    Then exactly 50 entries should be returned
    And they should be the 50 most recently queued

  # Why: Uniqueness invariant — a feature cannot be queued twice within the same correlation scope
  @task:TASK-PSM-008
  @boundary @negative
  Scenario: Queueing the same feature with the same correlation identifier twice is refused
    Given a build already exists for a feature under a specific correlation identifier
    When I queue the same feature again with the same correlation identifier
    Then the second queue attempt should be refused as a duplicate
    And only one build should remain recorded for that combination

  # Why: Status views bound the set of stages shown in the full detail view
  @task:TASK-PSM-009
  @boundary
  Scenario: Full status view includes the most recent stages per build
    Given a build has completed seventeen stages
    When I ask for status with full detail for that build
    Then at most the five most recent stages should be shown by default

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP C — Negative Cases
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Path allowlist is a safety boundary — queueing outside it must fail fast
  @task:TASK-PSM-008
  @negative
  Scenario: Queueing a build against a repository path outside the allowlist is refused
    Given a repository path that is not on the allowlist
    When I attempt to queue a feature for that repository
    Then the queue command should be refused with an unauthorised-path error
    And no new build should be recorded
    And no message should be published to the pipeline

  # Why: Active-duplicate guard — a feature already in flight cannot be re-queued
  @task:TASK-PSM-008
  @negative
  Scenario: Queueing a feature that already has an in-flight build is refused
    Given a build for a feature is currently pending pickup, preparing, running, or paused
    When I queue the same feature again
    Then the queue command should be refused as a duplicate in-flight build
    And the existing build should be unaffected

  # Why: Skip is only meaningful on a paused build awaiting review
  @task:TASK-PSM-011
  @negative
  Scenario: Skipping a build that is not paused is refused
    Given the pipeline is running a build that is not paused for review
    When I ask to skip the current stage of that build
    Then the skip command should be refused with an error
    And no skip decision should be sent to the pipeline

  # Why: Cancel resolves through the build history; missing builds should be reported, not crashed
  @task:TASK-PSM-011
  @negative
  Scenario: Cancelling a feature with no active or recent builds is refused
    Given there is no build on record for a given feature
    When I ask to cancel that feature
    Then the cancel command should be refused with a not-found error

  # Why: Crash during preparation should be surfaced as a failure, not a silent hang
  @task:TASK-PSM-004
  @negative
  Scenario: A feature description that fails validation causes preparation to fail
    Given a build has been picked up and its feature description is invalid
    When preparation attempts to validate the description
    Then the build should transition from preparation to failed
    And the build should record a structured reason describing the validation problem

  # Why: Hard-stop gate decision halts the build and is not retryable by the pipeline itself
  @task:TASK-PSM-004
  @negative
  Scenario: A hard-stop gate decision during running transitions the build to failed
    Given a running build has just produced a stage outcome that triggers a hard-stop decision
    When the gate resolves with no retry path
    Then the build should transition from running to failed
    And the completion time of the build should be recorded

  # Why: State machine invariant — transitions that are not in the allowed table are rejected
  @task:TASK-PSM-004
  @negative
  Scenario: Attempting to transition a build through an invalid path is refused
    Given a build is currently pending pickup
    When the pipeline attempts to transition that build directly to running without preparing first
    Then the transition should be refused as invalid
    And the build should remain pending pickup

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP D — Edge Cases
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Crash during preparation — redelivery restarts preparation from scratch
  @task:TASK-PSM-007
  @edge-case
  Scenario: A crash during preparation marks the build for redelivery
    Given a build had reached preparation
    When the pipeline process crashes before preparation completed
    And the pipeline process restarts and reconciles the build history
    Then the build should be marked as interrupted with a recoverable reason
    And the build should subsequently be picked up again and re-enter preparation

  # Why: Crash during running — retry-from-scratch policy
  @task:TASK-PSM-007
  @edge-case
  Scenario: A crash during running marks the build as interrupted and restarts it from scratch
    Given a build was in the running state when the pipeline crashed
    When the pipeline restarts and reconciles the build history
    Then the build should be marked as interrupted
    And the build should be re-picked up and restart from preparation

  # Why: Crash during finalisation — the PR may have been created, so operator reconciles
  @task:TASK-PSM-007
  @edge-case
  Scenario: A crash during finalisation marks the build as interrupted with an operator warning
    Given a build was finalising when the pipeline crashed
    When the pipeline restarts and reconciles the build history
    Then the build should be marked as interrupted
    And the recovery report should warn that the pull request may have been created and require manual reconciliation

  # Why: A paused build survives a crash — the approval request is re-issued on restart
  @task:TASK-PSM-007
  @edge-case
  Scenario: A paused build survives a pipeline crash and re-issues its approval request
    Given a build is paused awaiting a review decision
    When the pipeline crashes and restarts
    Then the build should remain paused after reconciliation
    And the pending approval request should be re-issued so reviewers can still respond

  # Why: Terminal states after a crash are a no-op — we must not restart completed builds
  @task:TASK-PSM-007
  @edge-case
  Scenario Outline: Builds in terminal states after a crash are not re-picked
    Given a build was already in the <terminal> state when the pipeline crashed
    When the pipeline restarts and reconciles the build history
    Then no new work should be started for that build
    And any outstanding delivery for that build should be acknowledged

    Examples:
      | terminal  |
      | complete  |
      | failed    |
      | cancelled |
      | skipped   |

  # Why: `forge cancel` during a paused state is modelled as a synthetic rejection
  @task:TASK-PSM-011
  @edge-case
  Scenario: Cancelling a paused build resolves its pending approval as a rejection
    Given a build is paused awaiting a review decision
    When I ask to cancel that build with a reason
    Then the cancel command should resolve the pending review as a rejection on my behalf
    And the build should transition from paused to cancelled
    And the reason I supplied should be recorded on the build

  # Why: `forge skip` during a flag-for-review pause continues the build without that stage
  @task:TASK-PSM-011
  @edge-case
  Scenario: Skipping a stage on a flagged-for-review pause resumes the build and marks the stage skipped
    Given a build is paused on a flag-for-review gate
    When I ask to skip the flagged stage with a reason
    Then the paused stage should be recorded as skipped with my reason
    And the build should resume from running
    And the overall build should still be allowed to complete successfully

  # Why: Sequential queue discipline — only one build runs at a time per project
  # [ASSUMPTION: confidence=medium] Sequential-queue scope is per-project; different
  # projects can run concurrently. The roadmap says "sequential build queue" without
  # scoping it explicitly.
  @task:TASK-PSM-006
  @edge-case
  Scenario: A second queued build waits until the first completes before starting
    Given one build is already running for a project
    When I queue a second feature for the same project
    Then the second build should be recorded as pending pickup
    And the second build should not begin preparation until the first build has reached a terminal state

  # Why: Watch mode streams state changes without blocking writes
  @task:TASK-PSM-009
  @edge-case
  Scenario: Watching status refreshes the view as the build progresses
    Given a build is running and moving through stages
    When I watch the status view
    Then the view should refresh to reflect each new stage as it begins
    And the view should stop refreshing once the build reaches a terminal state

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP E — Security
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Feature identifier is used in build identifier and on-disk paths — traversal must be refused
  # [ASSUMPTION: confidence=medium] Feature identifiers containing path-traversal
  # sequences (such as "../", "/", or "\") are rejected because feature_id is
  # interpolated into build_id and worktree paths.
  @task:TASK-PSM-001
  @edge-case @negative
  Scenario: Queueing with a feature identifier that contains path-traversal characters is refused
    When I attempt to queue a feature whose identifier contains traversal characters such as "../"
    Then the queue command should be refused with a validation error
    And no new build should be recorded
    And no message should be published to the pipeline

  # Why: Audit trail — the identity of the operator who triggered the build is preserved through cancel
  # [ASSUMPTION: confidence=medium] The cancelling operator is recorded distinctly from
  # the originating operator. The data model already supports this: `originating_user`
  # is carried on the build record; `responder` is captured on the approval-response
  # resolution that cancellation is modelled as.
  @task:TASK-PSM-011
  @edge-case
  Scenario: Cancelling a build records the cancelling operator even when different from the originator
    Given a build is currently running and was originated by one operator
    When a different operator cancels the build with a reason
    Then the build should transition to cancelled
    And the originating operator should remain recorded on the build
    And the cancelling operator and their reason should be recorded on the resolution

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP F — Concurrency
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Two simultaneous queue commands must both be durable and ordered
  @task:TASK-PSM-002
  @edge-case
  Scenario: Two features queued at the same instant both appear in history
    When two different features are queued at effectively the same instant
    Then both builds should be recorded as pending pickup
    And both builds should be assigned distinct build identifiers
    And both builds should appear in history with their original queue-time ordering preserved

  # Why: WAL guarantee — readers see a consistent snapshot even during active writes
  @task:TASK-PSM-002
  @edge-case
  Scenario: A concurrent reader sees a consistent snapshot while the pipeline is writing
    Given the pipeline is in the middle of recording a new stage outcome
    When a second reader asks for history at the same instant
    Then the reader should see a consistent snapshot from the last committed write
    And the reader should never observe a partially written stage

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP G — Data Integrity
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Invariant — a terminal build always has a recorded completion time
  @task:TASK-PSM-004
  @edge-case
  Scenario Outline: Any build that reaches a terminal state has a recorded completion time
    When a build reaches the <terminal> state
    Then the build should have a completion time recorded
    And no further state transitions should be permitted for that build

    Examples:
      | terminal  |
      | complete  |
      | failed    |
      | cancelled |
      | skipped   |

  # Why: Partial-failure between local write and pipeline publish must be recoverable, not silent
  # [ASSUMPTION: confidence=medium] When the pre-publish local write has succeeded
  # but the pipeline publish then fails, the build row remains visible as pending
  # pickup so the operator can reconcile or re-queue it. The CLI contract specifies
  # the write-before-publish order but does not specify the failure-mode visibility.
  @task:TASK-PSM-008
  @edge-case
  Scenario: A build row is written but the pipeline publish then fails
    Given queueing writes the build history row before publishing to the pipeline
    When the local write succeeds but the pipeline publish then fails
    Then the queue command should report a publish failure
    And the build should be visible as pending pickup so it can be reconciled or re-queued
    And the operator should be told the pipeline was not notified

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP H — Integration Boundaries
  # ─────────────────────────────────────────────────────────────────────────

  # Why: The CLI must fail cleanly when the pipeline messaging layer is unreachable
  @task:TASK-PSM-008
  @edge-case @negative
  Scenario: Queueing fails cleanly when the pipeline messaging layer is unreachable
    Given the pipeline messaging layer cannot be reached from the CLI
    When I attempt to queue a feature
    Then the queue command should fail with a messaging-layer error
    And the failure message should identify the messaging layer as the unreachable dependency
    And subsequent status queries should still work without the messaging layer
