# Generated by /feature-spec
# Feature: Specialist Agent Delegation (FEAT-FORGE-003)
# Stack: python
# Assumptions: 6 (see specialist-agent-delegation_assumptions.yaml)
# Generated: 2026-04-24T00:00:00Z

@feat-forge-003 @specialist-agent-delegation
Feature: Specialist Agent Delegation
  As Rich, the sole operator of Forge
  I want Forge to delegate domain judgement to fleet specialist agents via a single
    capability-driven dispatch path, with an unambiguous reply contract and a clear
    degraded-mode fallback when no specialist is available
  So that new specialist roles are reachable without code changes, silent round-trip
    failures from the LES1 class are prevented, and every dispatched decision feeds
    the gating layer with a Coach score, criterion breakdown, and detection findings

  Background:
    Given Forge is registered with the fleet and is watching fleet lifecycle events
    And the live capability cache is fresh

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP A — Key Examples
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Core happy-path — exact tool match, round-trip reply, gating input formed
  @task:TASK-SAD-011
  @key-example @smoke
  Scenario: Forge delegates a stage to a specialist advertising the exact tool
    Given a specialist agent advertises a tool matching the stage's requested capability
    When Forge dispatches the stage to that capability
    Then Forge should subscribe to a correlation-keyed reply channel before publishing the command
    And the specialist should publish its result on that correlation-keyed channel
    And Forge should feed the coach score, criterion breakdown, and detection findings into the gating layer

  # Why: Intent-pattern fallback — resolution still succeeds when no exact tool match exists
  @task:TASK-SAD-006
  @key-example
  Scenario: Forge falls back to intent-pattern matching when no tool match exists
    Given no specialist advertises the requested tool by exact name
    And a specialist advertises an intent pattern that covers the request at sufficient confidence
    When Forge resolves the capability
    Then Forge should select the intent-matching specialist
    And the resulting resolution record should mark the match source as an intent-pattern match

  # Why: Result parsing — Coach output may live at the top level or nested under result
  @task:TASK-SAD-005
  @key-example @smoke
  Scenario: Forge reads Coach output preferring top-level fields over nested result fields
    Given a specialist returns a result carrying both top-level Coach fields and nested Coach fields
    When Forge parses the reply
    Then Forge should use the top-level coach score, criterion breakdown, and detection findings
    And the nested fields should be retained only as fallback evidence

  # Why: Retry path — reasoning loop can re-dispatch with additional context after a soft failure
  # [ASSUMPTION: confidence=medium] Retry is reasoning-model-driven; no fixed max-retry count is enforced at the dispatch layer
  @task:TASK-SAD-007
  @key-example
  Scenario: Forge retries a failed dispatch with additional context on the second attempt
    Given a first dispatch to a specialist returns an error result
    When Forge decides to retry the stage with additional context
    Then Forge should issue a new dispatch with a fresh correlation
    And the additional context should be carried in the retry command
    And the retry attempt should be recorded alongside the original attempt

  # Why: Outcome correlation — discovery records are linked back to their downstream outcome
  @task:TASK-SAD-009
  @key-example
  Scenario: Forge links each capability resolution to its downstream outcome
    Given Forge has dispatched to a resolved specialist
    When the specialist's reply is received and the gate decision is produced
    Then the resolution record should be linked to that gate decision as its outcome
    And the resolution record should be marked as having its outcome correlated

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP B — Boundary Conditions
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Just-inside boundary — intent match at exactly the minimum confidence is accepted
  # [ASSUMPTION: confidence=high] Intent-fallback minimum confidence is 0.7 (DM-discovery §3)
  @task:TASK-SAD-006
  @boundary
  Scenario: An intent match at exactly the minimum confidence is accepted
    Given no specialist advertises the requested tool by exact name
    And a single specialist advertises the intent at exactly the minimum confidence threshold
    When Forge resolves the capability
    Then the specialist should be selected
    And the resolution should record the match source as an intent-pattern match

  # Why: Just-outside boundary — intent match below threshold is rejected
  @task:TASK-SAD-006
  @boundary @negative
  Scenario: An intent match below the minimum confidence is treated as unresolved
    Given no specialist advertises the requested tool by exact name
    And the only intent-pattern match is just below the minimum confidence threshold
    When Forge resolves the capability
    Then no specialist should be selected
    And the resolution should record the match source as unresolved

  # Why: Just-inside boundary — reply arriving inside the local timeout is accepted
  # [ASSUMPTION: confidence=high] Forge-side hard dispatch timeout default is 900 seconds (API-nats-agent-dispatch §5)
  @task:TASK-SAD-004
  @boundary
  Scenario: A reply received just before the local timeout succeeds
    Given Forge has dispatched a command with the default local timeout
    When the specialist's reply arrives just before the local timeout would have fired
    Then the reply should be accepted as the authoritative outcome
    And no timeout handling should run

  # Why: Just-outside boundary — reply arriving after the local timeout is not honoured
  @task:TASK-SAD-004
  @boundary @negative
  Scenario: A reply received after the local timeout is not used
    Given Forge has dispatched a command with the default local timeout
    When no reply arrives before the local timeout fires
    Then Forge should synthesise a timeout result for the reasoning loop
    And any reply that arrives afterwards should be ignored

  # Why: Tie-break by trust tier — core beats specialist beats extension at equal confidence
  @task:TASK-SAD-006
  @boundary
  Scenario Outline: Trust-tier ranking decides between otherwise-equivalent specialists
    Given two specialists advertise the same capability at the same confidence and queue depth
    And one is in the <higher_tier> trust tier and the other is in the <lower_tier> trust tier
    When Forge resolves the capability
    Then Forge should select the <higher_tier> specialist
    And the non-selected specialist should appear in the competing agents list

    Examples:
      | higher_tier | lower_tier |
      | core        | specialist |
      | specialist  | extension  |

  # Why: Tie-break by queue depth — lowest queue wins at equal tier and confidence
  @task:TASK-SAD-006
  @boundary
  Scenario: Lowest queue depth wins when trust tier and confidence are equal
    Given two specialists advertise the same capability at the same trust tier and confidence
    And one specialist has a lighter queue than the other
    When Forge resolves the capability
    Then Forge should select the specialist with the lighter queue
    And the non-selected specialist should appear in the competing agents list

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP C — Negative Cases
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Unresolved capability — no specialist matches and reasoning must decide next move
  @task:TASK-SAD-009
  @negative
  Scenario: No matching specialist triggers the degraded reasoning path
    Given no specialist advertises the requested tool or an intent-pattern match
    When Forge attempts to dispatch the stage
    Then Forge should synthesise a degraded result carrying the unresolved capability description
    And the reasoning loop should receive the degraded result as the outcome of the stage

  # Why: Degraded agents are excluded — a specialist that reports degraded status is not selected
  @task:TASK-SAD-006
  @negative
  Scenario: A specialist reporting degraded status is excluded from resolution
    Given only one specialist advertises the requested capability
    And that specialist's latest heartbeat reports a degraded status
    When Forge resolves the capability
    Then the specialist should not be selected
    And the resolution should record the match source as unresolved

  # Why: Specialist error — the specialist answered, but the outcome is an error
  @task:TASK-SAD-005
  @negative
  Scenario: A specialist error result is surfaced to the reasoning loop
    Given Forge has dispatched a command to a specialist
    When the specialist replies with an error result carrying an explanation
    Then the error explanation should be visible to the reasoning loop
    And Forge should not auto-approve the stage on the error result

  # Why: PubAck is not success — the audit stream may ack quickly and Forge must still wait for the reply
  @task:TASK-SAD-003
  @negative
  Scenario: A fast publish acknowledgement is not treated as the specialist's answer
    Given Forge has subscribed to the correlation-keyed reply channel before publishing
    When the fleet bus acknowledges the publish quickly but no specialist reply has arrived
    Then Forge should continue waiting for the specialist's reply on the correlation-keyed channel
    And the publish acknowledgement should not be recorded as a successful dispatch

  # Why: Wrong correlation — a stray reply for a different request must not be consumed
  @task:TASK-SAD-003
  @negative
  Scenario: A reply addressed to a different correlation is not consumed
    Given Forge is waiting on a correlation-keyed reply channel for a specific request
    When a reply for a different request is published on a different correlation-keyed channel
    Then Forge should not consume that reply
    And Forge should continue waiting for the reply matching its own correlation

  # Why: Missing Coach output — without a Coach score the gate cannot auto-approve
  # [ASSUMPTION: confidence=high] Gate fallback when Coach score is absent is FLAG_FOR_REVIEW (API-nats-agent-dispatch §6)
  @task:TASK-SAD-005
  @negative
  Scenario: A reply that omits the Coach score cannot auto-approve the stage
    Given a specialist replies with a successful result that carries no Coach score
    When Forge evaluates the stage's gate
    Then the gate should default to flagging the stage for human review
    And the reason for the flag should cite the missing Coach score

  # Why: Malformed reply — a reply that fails schema validation is treated as an error, not success
  @task:TASK-SAD-005
  @negative
  Scenario: A malformed reply envelope is treated as an error outcome
    Given a reply arrives on the correlation-keyed channel but fails envelope validation
    When Forge observes the reply
    Then Forge should treat the dispatch as failed with a schema-validation reason
    And Forge should not feed the malformed payload into the gating layer

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP D — Edge Cases
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Write-before-send invariant — the resolution record is persisted before the command is published
  @task:TASK-SAD-006
  @edge-case
  Scenario: The capability resolution is persisted before the command is published
    Given Forge is about to dispatch to a resolved specialist
    When Forge publishes the dispatch command
    Then the capability resolution record should already be persisted
    And the persisted resolution should reference the agent that the command was sent to

  # Why: Subscribe-before-publish invariant — per LES1, the reply channel must exist before the command goes out
  @task:TASK-SAD-003
  @edge-case
  Scenario: The reply subscription is established before the command is published
    Given Forge is about to dispatch to a resolved specialist
    When Forge publishes the dispatch command
    Then the subscription to the correlation-keyed reply channel should already be active
    And it should remain active until either the reply arrives or the local timeout fires

  # Why: Unsubscribe on timeout — the one-shot subscription is released to prevent leaks
  @task:TASK-SAD-003
  @edge-case
  Scenario: The correlation-keyed subscription is released after a timeout
    Given Forge has dispatched a command and begun waiting for a reply
    When the local timeout fires before any reply arrives
    Then Forge should release the correlation-keyed subscription
    And any subsequent late reply on that channel should not be delivered to Forge

  # Why: Cache freshness — a specialist joining mid-build becomes resolvable without restart
  # [ASSUMPTION: confidence=high] Discovery cache TTL is 30 seconds (DM-discovery §1)
  @task:TASK-SAD-006
  @edge-case
  Scenario: A specialist that joins during a build becomes resolvable on the next resolution
    Given Forge has already resolved an earlier stage against the current fleet
    When a new specialist registers that advertises a capability Forge will need
    And Forge resolves the next stage
    Then the newly-registered specialist should be considered during resolution

  # Why: Cache invalidation — a specialist that leaves must not be selected afterwards
  @task:TASK-SAD-006
  @edge-case
  Scenario: A specialist that deregisters after an earlier stage is not selected for the next one
    Given the specialist that served an earlier stage has deregistered
    When Forge resolves the next stage against the same capability
    Then the deregistered specialist should not be selected
    And resolution should fall back to another matching specialist or to the unresolved path

  # Why: Async-mode dispatch — long-running work returns a run identifier to be polled
  # [ASSUMPTION: confidence=high] Advisory specialist-side command timeout default is 600 seconds (API-nats-agent-dispatch §3.2)
  @task:TASK-SAD-008
  @edge-case
  Scenario: An async-mode dispatch returns a run identifier for later polling
    Given the resolved specialist advertises the capability as long-running
    When Forge dispatches the command
    Then the specialist's first reply should carry a run identifier rather than a final result
    And Forge should poll for the final result using the capability's status tool

  # Why: Concurrent dispatches — two simultaneous dispatches must not cross wires
  @task:TASK-SAD-003
  @edge-case @concurrency
  Scenario: Two concurrent dispatches to the same specialist keep their replies separate
    Given Forge has two stages ready to dispatch at the same time
    And both stages resolve to the same specialist
    When Forge publishes both commands
    Then each dispatch should subscribe to its own correlation-keyed reply channel
    And each reply should be delivered to the dispatch that issued its correlation

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP E — Security / Concurrency / Data Integrity / Integration
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Reply authenticity — only the resolved specialist's reply completes the round-trip
  @task:TASK-SAD-003
  @edge-case @security
  Scenario: A reply from a source other than the resolved specialist is not trusted
    Given Forge has dispatched a command to a specific resolved specialist
    When a reply arrives on the correlation-keyed channel whose source identifier is a different agent
    Then Forge should not accept the reply as the specialist's answer
    And Forge should continue to wait for the resolved specialist's reply or for the local timeout

  # Why: Secret hygiene — dispatched parameters may carry sensitive details that must not be persisted
  @task:TASK-SAD-002
  @edge-case @security
  Scenario: Dispatch parameters flagged as sensitive are not persisted in the resolution record
    Given a stage dispatches parameters that include fields marked as sensitive
    When Forge records the capability resolution
    Then the persisted resolution should not contain the sensitive parameter values
    And the pipeline history view of this dispatch should describe only non-sensitive fields

  # Why: Trust-tier is authoritative — a lower-trust extension cannot override a core specialist for the same tool
  @task:TASK-SAD-006
  @edge-case @security
  Scenario: An extension-tier specialist cannot shadow a core-tier specialist for the same tool
    Given a core-tier specialist and an extension-tier specialist both advertise the same tool
    When Forge resolves the capability
    Then the core-tier specialist should be selected
    And the extension-tier specialist should appear only in the competing agents list

  # Why: Snapshot stability — an in-flight resolution must not see a cache swap mid-call
  @task:TASK-SAD-006
  @edge-case @concurrency
  Scenario: A fleet event that invalidates the cache does not disturb an in-flight resolution
    Given Forge is in the middle of resolving a capability against the current fleet snapshot
    When a fleet event arrives that invalidates the cache
    Then the in-flight resolution should complete against the snapshot it already read
    And the next resolution after the in-flight one should use the refreshed snapshot

  # Why: Determinism — concurrent resolutions with the same inputs must produce the same choice
  @task:TASK-SAD-006
  @edge-case @concurrency
  Scenario: Two concurrent resolutions for the same capability produce the same choice
    Given two stages resolve the same capability at the same time against the same fleet snapshot
    When both resolutions complete
    Then both should select the same specialist
    And the competing-agents list should be consistent across the two resolutions

  # Why: Exactly-once delivery — a duplicate reply on the same correlation is ignored
  @task:TASK-SAD-003
  @edge-case @data-integrity
  Scenario: A duplicate reply on the same correlation-keyed channel is ignored
    Given Forge has already accepted a reply on a correlation-keyed channel
    When a second reply for the same correlation is published afterwards
    Then Forge should not reprocess the duplicate reply
    And the gate decision derived from the first reply should stand

  # Why: Bus outage — a disconnect while waiting must not hang the pipeline silently
  @task:TASK-SAD-009
  @edge-case @integration
  Scenario: The fleet bus disconnects while Forge is waiting for a reply
    Given Forge has dispatched a command and is waiting for the specialist's reply
    When the fleet bus becomes unreachable before the reply arrives
    Then Forge should treat the dispatch as failed and surface the outcome to the reasoning loop
    And the pipeline should not wait indefinitely for a reply that cannot arrive

  # Why: Registry outage — Forge keeps serving from the last known snapshot rather than stalling
  @task:TASK-SAD-009
  @edge-case @integration
  Scenario: A registry read failure during cache refresh falls back to the last-known snapshot
    Given the live fleet registry is temporarily unreadable
    When Forge needs to resolve a capability and its cache has just expired
    Then Forge should resolve against the last-known fleet snapshot
    And the reasoning loop should be informed that the fleet view may be stale
