# Generated by /feature-spec
# Feature: Forge Production Image (FEAT-FORGE-009)
# Stack: python
# Assumptions: 10 (see forge-production-image_assumptions.yaml)
# Generated: 2026-04-30T00:00:00Z

@feat-forge-009 @production-image
Feature: Forge Production Image
  As Rich, the sole operator of Forge
  I want a canonical, multi-stage container image that ships the full
    forge CLI surface and runs forge serve as its long-lived daemon
  So that the LES1 parity gates (CMDW, PORT, ARFS, canonical-freeze)
    of FEAT-FORGE-008 Phase 6 can run unblocked, the FinProxy first-run
    runbook executes verbatim, and no canonical build path depends on
    a developer-host editable install or a sibling working tree

  Background:
    Given the forge repository is checked out at a fresh clone
    And the sibling nats-core working tree is available alongside it
    And no Dockerfile-side mutation of pyproject.toml or .env is required

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP A — Key Examples
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Core build path — establishes that the canonical image can be produced
  #      from a clean clone using the runbook-documented invocation. (AC-A, AC-E)
  @task:TASK-F009-005
  @key-example @smoke
  Scenario: The production image builds from a fresh clone using the canonical invocation
    Given a clean checkout of the forge repository
    And the nats-core sibling source is reachable as a named build context
    When the operator runs the canonical production-image build command
    Then a tagged production image should be produced
    And the image should have been assembled via two stages — a builder stage and a slimmer runtime stage
    And the install command used inside the image should match the install command documented in the validation runbook word-for-word

  # Why: Confirms the CLI surface (PORT structural prerequisite) is intact in the image
  @task:TASK-F009-001
  @key-example @smoke
  Scenario: The production image exposes the full forge CLI surface
    Given a built production image
    When the operator runs the forge help command inside the container
    # [ASSUMPTION: confidence=high] (ASSUM-008) Documented subcommands are queue, status, history, cancel, skip, serve
    Then the help output should list every documented subcommand including queue, status, history, cancel, skip, and the new serve subcommand
    And no subcommand should be hidden or missing

  # Why: CMDW round-trip — the daemon must subscribe and receive a real
  #      published payload, not silently fail to register the consumer.
  @task:TASK-F009-003
  @key-example @smoke
  Scenario: The production image runs forge serve as a long-lived daemon and receives a queued build
    Given a built production image
    And a reachable JetStream broker
    When the container is started with forge serve as its main process
    And a build payload is published to the build-queued subject
    Then the daemon should remain running as the container's main process
    And the daemon should receive the published payload through its JetStream subscription
    And the receipt should be observable to the operator without exec'ing into the container

  # Why: ARFS structural check — every fleet tool must survive into the runtime image
  @task:TASK-F009-006
  @key-example
  Scenario: The agent manifest inside the image lists every fleet tool
    Given a built production image
    When the manifest-build code path runs inside the container
    # [ASSUMPTION: confidence=high] (ASSUM-009) Canonical fleet tools per src/forge/fleet/manifest.py
    Then the resulting manifest should include forge_greenfield, forge_feature, forge_review_fix, forge_status, and forge_cancel
    And each tool should be reachable via the installed forge package — not via mounted source

  # Why: Canonical-freeze gate — verbatim runbook execution from a clean machine
  @task:TASK-F009-008
  @key-example
  Scenario: The runbook Phase 6 build invocation succeeds verbatim
    Given a clean machine with only the documented prerequisites installed
    When the operator copy-pastes the Phase 6.1 build command from the validation runbook
    Then the image should build without any host-side patching of pyproject.toml, .env, or symlinks
    And any required setup should already be present as copy-pastable shell blocks at the top of Phase 6.1

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP B — Boundary Conditions
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Just-inside boundary — image must start without provider-key envs set
  @task:TASK-F009-003
  @boundary
  Scenario: The container starts cleanly when no provider API keys are supplied
    Given a built production image
    And no provider API key environment variables are set
    When the container is started with forge serve
    # [ASSUMPTION: confidence=medium] (ASSUM-002) Provider absence becomes a per-build error, not a startup error
    Then the daemon should start without error
    And the daemon should remain running until a build payload requires a provider

  # Why: Just-inside boundary — default NATS URL must work when env unset
  @task:TASK-F009-001
  @boundary
  Scenario: forge serve binds to the documented default NATS URL when no override is supplied
    Given a built production image
    And the FORGE_NATS_URL environment variable is not set
    When the container is started with forge serve
    # [ASSUMPTION: confidence=high] (ASSUM-001) Default broker URL is nats://127.0.0.1:4222 (src/forge/cli/queue.py:265)
    Then the daemon should attempt its JetStream subscription against the documented default broker URL

  # Why: Just-inside boundary — the literal-match install command (LES1 §3 DKRX)
  @task:TASK-F009-005
  @boundary
  Scenario Outline: The install command in the Dockerfile matches the runbook documentation
    Given the Dockerfile in the repository root
    When the install command is extracted from the builder stage
    Then it should match the install command documented in <runbook_section> exactly

    Examples:
      | runbook_section                          |
      | RUNBOOK-FEAT-FORGE-008 Phase 0.4         |
      | RUNBOOK-FEAT-FORGE-008 Phase 6.1         |

  # Why: Just-outside boundary — image-size regression is a CI-visible gate
  @task:TASK-F009-007
  @boundary @negative
  Scenario: The image fails the size regression check when its uncompressed size exceeds the budget
    Given a build pipeline that enforces an image-size budget
    # [ASSUMPTION: confidence=low] (ASSUM-003) Budget is 1.0 GB uncompressed (scoping §11.7 cites 600–900 MB typical)
    When a built image exceeds the documented budget
    Then the size regression check should fail
    And the failure should name the size budget and the actual image size

  # Why: Health probe boundary — healthy vs. unhealthy is the contract
  @task:TASK-F009-004
  @boundary
  Scenario Outline: The container health probe reflects the daemon's subscription state
    Given a running container started with forge serve
    # [ASSUMPTION: confidence=medium] (ASSUM-004) Health is exposed via an HTTP /healthz endpoint
    # [ASSUMPTION: confidence=low] (ASSUM-005) Health probe / serve port is 8080
    When the daemon's JetStream subscription is in <subscription_state>
    Then the container's reported health status should be <health_status>

    Examples:
      | subscription_state           | health_status |
      | live and ready               | healthy       |
      | not yet established          | unhealthy     |
      | dropped without recovery yet | unhealthy     |

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP C — Negative Cases
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Hard CI gate — no real provider keys may be baked into any image layer
  @task:TASK-F009-007
  @negative @smoke
  Scenario: The image contains no real provider API keys in any layer
    Given a built production image
    When every layer of the image is scanned for provider key material
    Then no real provider API key should be present in any layer
    And the build pipeline should fail if such a key is detected

  # Why: Container must not run as root — security baseline
  @task:TASK-F009-002
  @negative @smoke
  Scenario: The container runs as a non-root user
    Given a built production image
    When the container is started with any documented subcommand
    Then the running process should belong to a dedicated non-root user
    And that user should not have administrative privileges inside the container

  # Why: Missing build context for nats-core must fail clearly, not silently
  @task:TASK-F009-005
  @negative
  Scenario: The build fails with a clear diagnostic when the nats-core build context is missing
    Given a build invocation that omits the nats-core named build context
    When the operator attempts to build the image
    Then the build should fail before producing a tagged image
    And the failure message should name the missing build context and how to supply it

  # Why: Editable installs must not survive into the runtime stage (LES1 §3 DKRX)
  @task:TASK-F009-005
  @negative
  Scenario: The runtime image contains no editable installs
    Given a built production image
    When the installed forge distribution is inspected inside the runtime stage
    Then forge should be present as a regular installed distribution
    And no .pth-style editable install pointer should be present in the runtime venv

  # Why: forge serve must not silently accept missing canonical configuration
  @task:TASK-F009-003
  @negative
  Scenario: forge serve refuses to start when its required configuration is invalid
    Given a built production image
    And a configuration file that fails its canonical schema check
    When the container is started with forge serve against that configuration
    Then the daemon should refuse to start
    And the container should exit with a non-zero status
    And the operator should see a diagnostic naming the offending configuration field

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP D — Edge Cases
  # ─────────────────────────────────────────────────────────────────────────

  # Why: CMDW failure mode — stale image silently fails to receive payloads
  @task:TASK-F009-006
  @edge-case @regression
  Scenario: A stale image whose fleet manifest has drifted is detected before a build is dispatched
    Given a production image whose embedded manifest is older than the canonical fleet manifest
    When the operator queues a build that targets a tool added after the image was built
    Then the dispatch should refuse to route the build to the stale image
    And the operator should be told that the image is out of date and how to refresh it

  # Why: Concurrency — two daemons must not double-process the same payload
  @task:TASK-F009-003
  @edge-case
  Scenario: Two concurrently running daemons do not double-process the same queued build
    Given two containers running forge serve against the same JetStream broker
    # [ASSUMPTION: confidence=medium] (ASSUM-006) forge serve uses a single shared durable consumer named "forge-serve"
    When a single build payload is published to the build-queued subject
    Then the payload should be delivered to exactly one daemon
    And the other daemon should observe the build as already claimed

  # Why: NATS transient unavailability must not require a container restart
  @task:TASK-F009-003
  @edge-case
  Scenario: forge serve recovers automatically when the broker is briefly unavailable
    Given a running daemon with a live subscription
    When the JetStream broker becomes unavailable for a short interval
    And the broker becomes available again
    # [ASSUMPTION: confidence=low] (ASSUM-007) Reconnect bounded by JetStream durable consumer redelivery defaults
    Then the daemon should re-establish its subscription without operator intervention
    And buffered payloads published during the outage should be delivered once the subscription is restored

  # Why: Cache-poisoning regression — pyproject changes must invalidate the install layer
  @task:TASK-F009-006
  @edge-case @regression
  Scenario: A pyproject change actually changes the installed dependencies in the rebuilt image
    Given a previous production image built against pyproject revision X
    And a pyproject revision Y that adds or upgrades a dependency
    When the image is rebuilt against revision Y
    Then the installed dependency set in the rebuilt image should reflect revision Y
    And no stale install layer from revision X should be reused incorrectly

  # Why: CI workflow scope — guards the three trigger paths
  @task:TASK-F009-007
  @edge-case @regression
  Scenario Outline: The CI image-build workflow runs on pull requests touching the production-image surface
    Given a pull request that changes <changed_path>
    When the CI pipeline is evaluated for that pull request
    Then the production-image build-and-smoke-test workflow should be triggered

    Examples:
      | changed_path     |
      | Dockerfile       |
      | pyproject.toml   |
      | src/forge/       |

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP E1 — Edge Cases / Security
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Floating tags re-resolve silently — supply-chain integrity gate
  @task:TASK-F009-002
  @edge-case @smoke
  Scenario: Base images are pinned to an immutable digest
    Given the Dockerfile in the repository root
    # [ASSUMPTION: confidence=medium] (ASSUM-010) Base is python:3.14-slim-bookworm pinned by sha256 in both stages
    When the FROM directives are inspected
    Then every base image reference should be pinned to an immutable content digest
    And no FROM directive should rely on a floating tag alone

  # Why: Process must not escape its declared write surfaces
  @task:TASK-F009-003
  @edge-case
  Scenario: forge serve cannot write outside the declared artefact volume
    Given a running container started with forge serve
    When the daemon attempts to write to a path outside its declared artefact registry volume
    Then the write should be rejected by the container's filesystem permissions
    And the daemon should surface the rejection through its normal error channel rather than crash

  # Why: Production image must not ship interactive remote-access surfaces
  @task:TASK-F009-005
  @edge-case
  Scenario: The container exposes no interactive remote-access endpoint
    Given a built production image
    When the image's exposed ports and runtime processes are inspected
    Then no SSH server, no remote debugger, and no interactive shell endpoint should be listening
    And only the documented serve and health probe ports should be exposed

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP E2 — Edge Cases / Data Integrity
  # ─────────────────────────────────────────────────────────────────────────

  # Why: A crashed build must not vanish — JetStream redelivery is the safety net
  @task:TASK-F009-003
  @edge-case @regression
  Scenario: A build that crashes mid-execution remains redeliverable
    Given a daemon that has received a build payload
    When the daemon process crashes before acknowledging the payload
    Then the payload should remain pending on the JetStream consumer
    And a subsequent daemon should pick the payload up on its next subscription poll

  # Why: Artefact registry must survive container lifecycle — operator data invariant
  @task:TASK-F009-003
  @edge-case
  Scenario: The artefact registry filesystem persists across container restarts
    Given a running container with its artefact volume mounted at the documented path
    And the daemon has produced build artefacts during execution
    When the container is stopped and restarted against the same volume
    Then the previously produced artefacts should still be readable
    And no artefact metadata should have been silently truncated

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP E3 — Edge Cases / Integration Boundaries
  # ─────────────────────────────────────────────────────────────────────────

  # Why: One bad provider must not poison the daemon for all other builds
  @task:TASK-F009-003
  @edge-case
  Scenario: A failing provider for one build does not crash the daemon for unrelated builds
    Given a daemon currently processing a build that targets an unavailable provider
    When the affected build fails because the provider is unreachable
    Then the daemon should mark only that build as failed with a diagnostic naming the provider
    And the daemon should remain available to receive and process subsequent builds

  # Why: Architecture mismatch must fail fast — silent emulation is a debugging trap
  @task:TASK-F009-007
  @edge-case
  Scenario: An architecture-mismatched pull fails fast with a clear diagnostic
    Given a published production image whose declared platform does not match the host
    When the operator attempts to run the image on the mismatched host
    Then the runtime should refuse to start the container
    And the operator should see a diagnostic naming the expected and actual platforms
