# Generated by /feature-spec
# Feature: Wire the production pipeline orchestrator into forge serve (FEAT-FORGE-010)
# Stack: python
# Assumptions: 18 (see forge-serve-orchestrator-wiring_assumptions.yaml)
# Generated: 2026-05-02T00:00:00Z

@feat-forge-010 @forge-serve-orchestrator-wiring
Feature: Wire the production pipeline orchestrator into forge serve
  As Rich, the sole operator of Forge
  I want forge serve to host the full pipeline orchestrator end-to-end in production
  So that a queued build runs through the canonical Mode A chain, publishes the
    real lifecycle envelope sequence back to JetStream with correlation-id
    threading, and survives crash + restart — instead of being acked into a
    receipt-only stub

  Background:
    Given a JetStream PIPELINE stream is reachable
    And a SQLite database is the durable source of truth for build state
    And the eight pipeline lifecycle subjects are the published contract
    And the build-queued payload conforms to the canonical schema
    And forge serve is running as the canonical daemon

  # ===========================================================================
  # GROUP A — Key Examples
  # ===========================================================================

  # Why: Capstone integration — a queued build runs end-to-end and publishes the full lifecycle envelope sequence back
  @task:TASK-FW10-011
  @key-example @smoke
  Scenario: A queued build runs end-to-end through the orchestrator and publishes the full lifecycle envelope sequence
    Given a build-queued envelope is delivered for a feature in greenfield mode
    When forge serve consumes the envelope
    Then the orchestrator should run the build through every approved stage to a terminal state
    And the published lifecycle subjects should begin with build-started for that feature
    And every stage transition should publish one stage-complete for that feature in transition order
    And the published lifecycle subjects should end with either build-complete or build-failed for that feature

  # Why: Production wiring — the orchestrator chain must be constructed at daemon startup, not deferred to a stub
  # [ASSUMPTION: confidence=high] (ASSUM-002) Supervisor, PipelineConsumerDeps, PipelineLifecycleEmitter, PipelinePublisher, ForwardContextBuilder, and the autobuild_runner subagent are all constructed at daemon startup
  @task:TASK-FW10-001
  @key-example @smoke
  Scenario: Daemon startup composes the full orchestrator chain in production
    Given forge serve has just started
    When the daemon's startup completes
    Then a supervisor should be constructed
    And a pipeline consumer dependency container should be constructed against the daemon's NATS client
    And a pipeline lifecycle emitter should be constructed against the daemon's NATS client
    And the autobuild_runner asynchronous subagent should be registered as an addressable graph
    And the receipt-only dispatch stub should not be reachable from any production code path

  # Why: Correlation-id is the audit thread linking every envelope of a build back to its trigger
  @task:TASK-FW10-011
  @key-example
  Scenario: Every published envelope of a build threads the inbound correlation identifier
    Given a build-queued envelope arrives with a correlation identifier
    When the build runs through to a terminal state
    Then every lifecycle envelope published for that build should carry that same correlation identifier
    And no published envelope for that build should carry a different correlation identifier

  # Why: autobuild_runner runs as a long-running AsyncSubAgent so the supervisor stays responsive
  # [ASSUMPTION: confidence=high] (ASSUM-003) autobuild_runner uses the DeepAgents AsyncSubAgent middleware via start_async_task with ASGI transport, registered as a separate graph in langgraph.json
  @task:TASK-FW10-008
  @key-example
  Scenario: The autobuild stage runs as an asynchronous subagent and the supervisor stays responsive
    Given the build has reached the autobuild stage
    When the supervisor dispatches the autobuild
    Then the dispatch should return a task identifier without waiting for autobuild to complete
    And while the autobuild is in flight the supervisor should continue to answer status queries
    And the autobuild's progress should be observable via the asynchronous task state channel

  # Why: Per-stage envelopes are emitted by real stage transitions, not by a synthetic dispatch placeholder
  # [ASSUMPTION: confidence=medium] (ASSUM-004) The synthetic dispatch-stage envelope from the superseded TASK-FORGE-FRR-001 is not preserved; only real stage transitions emit stage-complete
  @task:TASK-FW10-011
  @key-example @regression
  Scenario: Each real stage transition publishes its own stage-complete envelope
    Given the build progresses through more than one stage
    When each stage transition records its outcome
    Then one stage-complete envelope should be published per real stage transition
    And no envelope should bear a synthetic dispatch-stage label
    And each envelope's status, target_kind, target_identifier and stage_label should reflect the real transition

  # Why: A build-started precedes the first stage and a terminal envelope closes the build
  @task:TASK-FW10-006
  @key-example
  Scenario: A build-started envelope is published before the first stage and a terminal envelope closes the build
    Given a build has been picked up from the queue
    When the build progresses to its first stage
    Then a build-started envelope for that build should already have been published
    And on terminal success the lifecycle should close with a build-complete envelope
    And on terminal failure the lifecycle should close with a build-failed envelope

  # Why: A single shared NATS client serves both the inbound consumer and the outbound publisher — no second connection
  # [ASSUMPTION: confidence=high] (ASSUM-011) Opening a second NATS connection for outbound publish is forbidden in a single-process daemon
  @task:TASK-FW10-006
  @key-example @smoke
  Scenario: The consumer and the publisher share the daemon's single NATS connection
    Given forge serve has opened its NATS connection at startup
    When the consumer attaches and the publisher emits envelopes
    Then both should use the daemon's single NATS connection
    And no second connection to the broker should be established by the daemon

  # ===========================================================================
  # GROUP B — Boundary Conditions
  # ===========================================================================

  # Why: Sequential builds enforced at transport — max_ack_pending=1 is the structural invariant (ADR-ARCH-014)
  # [ASSUMPTION: confidence=high] (ASSUM-005, ASSUM-006) PIPELINE durable consumer is configured with max_ack_pending=1 and the canonical durable name "forge-serve"
  @task:TASK-FW10-001
  @boundary @smoke
  Scenario: The durable consumer is configured to enforce one outstanding build at a time
    Given forge serve has attached its durable consumer
    When the consumer's configuration is inspected
    Then the configured outstanding-acknowledgement limit should be one
    And the consumer's durable name should be the canonical pipeline durable name

  # Why: Just-inside boundary — the JetStream message is acked exactly when the build reaches a terminal state
  # [ASSUMPTION: confidence=high] (ASSUM-007) Forge acknowledges the inbound message only on a terminal state transition (COMPLETE / FAILED / CANCELLED / SKIPPED)
  @task:TASK-FW10-001
  @boundary
  Scenario Outline: The inbound JetStream message is acknowledged exactly when the build reaches a terminal state
    Given a build-queued envelope has been delivered
    When the build reaches the <terminal_state> state
    Then the corresponding JetStream message should be acknowledged
    And the queue slot should be released for the next build

    Examples:
      | terminal_state |
      | complete       |
      | failed         |
      | cancelled      |
      | skipped        |

  # Why: Just-outside boundary — paused builds do NOT ack and hold the queue position
  @task:TASK-FW10-010
  @boundary @negative
  Scenario: A paused build does not acknowledge its inbound JetStream message
    Given a build has reached a paused state awaiting human approval
    When the inbound JetStream message's acknowledgement state is inspected
    Then the message should remain unacknowledged
    And the queue slot should still be held by the paused build
    And no second build should be delivered until the paused build resolves

  # Why: Just-inside — minimal valid lifecycle: build-started, one stage-complete, build-complete
  @task:TASK-FW10-011
  @boundary
  Scenario: A minimal single-stage build publishes exactly the minimal envelope sequence
    Given the build's plan contains exactly one stage that transitions to a passed status
    When forge serve consumes the build-queued envelope and the build runs to terminal success
    Then exactly one build-started envelope should have been published for that build
    And exactly one stage-complete envelope should have been published for that build
    And exactly one build-complete envelope should have been published for that build

  # Why: Just-inside — the redelivery interval is bounded by the configured ack_wait
  # [ASSUMPTION: confidence=high] (ASSUM-008) ack_wait is configured to approximately one hour to cover the longest expected build
  @task:TASK-FW10-001
  @boundary
  Scenario: The configured ack_wait covers the longest expected build duration
    Given the durable consumer has been attached
    When the consumer's ack_wait is inspected
    Then it should be configured to a duration long enough to cover the longest expected build

  # ===========================================================================
  # GROUP C — Negative Cases
  # ===========================================================================

  # Why: Receipt-only stub is gone — production must dispatch through the real orchestrator
  @task:TASK-FW10-001
  @negative @regression
  Scenario: A queued build is no longer routed to a receipt-only stub
    Given forge serve has just started
    When a build-queued envelope arrives
    Then the dispatch should not log-and-return without running the orchestrator
    And the orchestrator should observe the inbound payload

  # Why: A malformed payload is rejected with a build-failed envelope (the contract failure mode)
  # [ASSUMPTION: confidence=high] (ASSUM-013) Validation failures publish build-failed with a malformed-payload reason and acknowledge the inbound message
  @task:TASK-FW10-009
  @negative
  Scenario: A malformed build-queued payload publishes a build-failed envelope and is acknowledged
    Given a build-queued envelope arrives whose payload does not match the expected schema
    When forge serve consumes the envelope
    Then a build-failed envelope should be published for the offending feature
    And the published envelope should record a malformed-payload failure reason
    And the inbound JetStream message should be acknowledged so the queue advances

  # Why: Duplicate detection — a previously-seen build is acked and skipped
  # [ASSUMPTION: confidence=high] (ASSUM-014) Duplicate detection uses a SQLite unique index on (feature_id, correlation_id)
  @task:TASK-FW10-009
  @negative
  Scenario: A duplicate build-queued envelope is acknowledged and skipped without re-running
    Given a build with the same feature identifier and correlation identifier has already been recorded
    When the duplicate envelope is delivered
    Then the orchestrator should not start a second run
    And the inbound message should be acknowledged
    And no new build-started envelope should be published for the duplicate

  # Why: Build path outside the worktree allowlist must publish build-failed (permission gate)
  # [ASSUMPTION: confidence=high] (ASSUM-015) A path outside the worktree allowlist publishes build-failed before any orchestrator dispatch
  @task:TASK-FW10-009
  @negative @security
  Scenario: A build whose feature configuration path falls outside the worktree allowlist is rejected
    Given a build-queued envelope references a feature configuration path outside the worktree allowlist
    When forge serve consumes the envelope
    Then a build-failed envelope should be published with a path-outside-allowlist failure reason
    And no orchestrator dispatch should be performed for that build

  # Why: A dispatch error must not take the daemon down — log + advance + continue
  @task:TASK-FW10-009
  @negative
  Scenario: A dispatch error is contained and the daemon continues to process the next build
    Given the orchestrator's dispatch raises an unexpected error during a build
    When forge serve handles the error
    Then the affected build should reach a failed terminal state and publish a build-failed envelope
    And the daemon should remain running
    And the daemon should continue to process subsequently delivered builds

  # Why: Publish failure does not corrupt the build's recorded state — SQLite is the source of truth (ADR-ARCH-008)
  @task:TASK-FW10-009
  @negative @regression
  Scenario: A failed lifecycle publish does not regress the build's recorded transition
    Given a stage has been recorded as transitioned in the durable history
    When the corresponding lifecycle envelope publish fails
    Then the recorded transition should still hold in the durable history
    And the build should continue to its next stage as if the publish had succeeded

  # ===========================================================================
  # GROUP D — Edge Cases
  # ===========================================================================

  # Why: Crash mid-build — JetStream redelivers, the daemon's reconciliation pair runs, the build resumes per anchor §5
  # [ASSUMPTION: confidence=high] (ASSUM-009) Both pipeline_consumer.reconcile_on_boot and forge.lifecycle.recovery.reconcile_on_boot are wired into the daemon startup
  @task:TASK-FW10-001
  @edge-case @regression
  Scenario: A crash mid-build is recovered after restart by the daemon's reconciliation routines
    Given a build was in a non-terminal state when forge serve crashed
    When forge serve restarts
    Then the daemon's startup should run both the consumer-side and lifecycle-side reconciliation routines
    And the unacknowledged inbound message should be redelivered
    And the build should re-enter the orchestrator from the recovery state defined by the durable history

  # Why: Paused build survives restart — re-emits BuildPaused + ApprovalRequest idempotently on correlation_id (ADR-ARCH-021)
  # [ASSUMPTION: confidence=medium] (ASSUM-010) The pause and resume lifecycle envelopes are wired in this feature; if it cannot be a one-line addition the pause/resume publish is split into a follow-up
  @task:TASK-FW10-010
  @edge-case
  Scenario: A paused build survives daemon restart and re-emits its approval request
    Given a build was paused awaiting human approval when forge serve crashed
    When forge serve restarts
    Then the build should re-enter the paused state
    And a build-paused envelope should be re-published for that build
    And the approval request should be re-published with the same correlation identifier
    And only the first approval response received should resume the build

  # Why: Approval round-trip — once the response arrives, build-resumed publishes and the autobuild continues
  @task:TASK-FW10-010
  @edge-case
  Scenario: An approval response resumes a paused build and publishes a build-resumed envelope
    Given a build is paused awaiting human approval
    When the approval response is received on the build's reply subject
    Then a build-resumed envelope should be published for that build
    And the orchestrator should advance to the next stage

  # Why: Two replicas behind the same durable name — one fetches the slot, the other idles (ADR-ARCH-027)
  @task:TASK-FW10-011
  @edge-case
  Scenario: Two replicas binding the same durable consumer split work as failover, not parallelism
    Given two forge serve replicas have attached to the same durable consumer
    When a build-queued envelope is delivered
    Then exactly one replica should fetch the message
    And the other replica should remain idle until the first replica's build reaches a terminal state

  # Why: Cancellation propagates through the async subagent — build-cancelled is the final envelope
  @task:TASK-FW10-002
  @edge-case
  Scenario: A cancel command propagates through the autobuild subagent and publishes a build-cancelled envelope
    Given a build is in flight in the autobuild stage
    When a cancel command is issued for that build
    Then the autobuild's asynchronous task should reach a cancelled state
    And a build-cancelled envelope should be published for that build
    And the build should reach a cancelled terminal state with no pull-request creation attempted

  # Why: SIGTERM during a non-terminal build does not ack the inbound message — JetStream redelivers on restart
  @task:TASK-FW10-001
  @edge-case
  Scenario: SIGTERM during a non-terminal build leaves the inbound message unacknowledged for redelivery
    Given a build is in a non-terminal state
    When forge serve receives SIGTERM
    Then the daemon should exit cleanly
    And the inbound JetStream message should remain unacknowledged
    And the message should be redelivered when forge serve restarts

  # ===========================================================================
  # GROUP E — Edge Case Expansion (security, data integrity, integration)
  # ===========================================================================

  # Why: Worktree confinement is a security invariant — autobuild_runner subagent must not escape the build's allowlist
  @task:TASK-FW10-002
  @security @edge-case
  Scenario: The autobuild_runner subagent writes only inside the build's worktree path
    Given a build is in flight in the autobuild stage with a configured worktree path
    When the autobuild_runner subagent performs filesystem writes
    Then every write should fall under the build's worktree allowlist
    And no write outside that allowlist should be performed by the subagent

  # Why: Approval responses are routed by correlation identifier — a mismatched response must not resume any build
  # [ASSUMPTION: confidence=high] (ASSUM-016) Approval reply subjects are correlation-keyed per DDR-001; mismatched responses are dropped
  @task:TASK-FW10-010
  @security @edge-case
  Scenario: An approval response with a mismatched correlation identifier does not resume any paused build
    Given a build is paused awaiting human approval with a known correlation identifier
    When an approval response arrives carrying a different correlation identifier
    Then the paused build should remain paused
    And no build-resumed envelope should be published for that build

  # Why: Lifecycle publish ordering is the audit invariant — build-started precedes stage-complete precedes terminal
  @task:TASK-FW10-011
  @data-integrity @edge-case
  Scenario: The published lifecycle envelope sequence respects the canonical ordering
    Given a build runs through more than one stage to a terminal state
    When the published lifecycle envelopes for that build are read in publish order
    Then the build-started envelope should appear before any stage-complete envelope
    And every stage-complete envelope should appear before the terminal envelope
    And the terminal envelope should appear exactly once

  # Why: Recovery contract — durable history is authoritative; the async_tasks state channel is advisory (DDR-006)
  # [ASSUMPTION: confidence=high] (ASSUM-017) On crash recovery the async_tasks channel is read as advisory; SQLite history is the authoritative source
  @task:TASK-FW10-001
  @data-integrity @edge-case
  Scenario: On daemon restart the durable history is the authoritative source for build state
    Given a build was in flight when forge serve crashed
    And the asynchronous task state channel and the durable history disagree about the build's status
    When forge serve restarts and reconciles the build
    Then the build's authoritative status should be read from the durable history
    And the asynchronous task state channel data should be treated as advisory only

  # Why: Per-stage envelopes from inside autobuild must be linkable back to the asynchronous task that produced them
  # [ASSUMPTION: confidence=medium] (ASSUM-018) Stage-complete envelopes emitted from within autobuild_runner set target_identifier to the subagent's task identifier and target_kind to subagent
  @task:TASK-FW10-002
  @data-integrity @edge-case
  Scenario: A stage-complete envelope emitted from within the autobuild subagent records the asynchronous task identifier
    Given the autobuild subagent has been dispatched with an asynchronous task identifier
    When the subagent's internal stage transition publishes a stage-complete envelope
    Then the published envelope's target_identifier should be the subagent's asynchronous task identifier
    And the published envelope's target_kind should indicate that the source is a subagent

  # Why: Fail fast at startup — the daemon must not silently degrade to a receipt-only path if NATS is unreachable
  @task:TASK-FW10-011
  @integration @edge-case
  Scenario: The daemon refuses to start if its NATS connection cannot be opened
    Given the configured JetStream broker is unreachable at startup
    When forge serve attempts to start
    Then the daemon should fail to start
    And the operator should see a diagnostic naming the unreachable broker
    And no orchestrator dispatch should be attempted

  # Why: Healthz must reflect orchestrator readiness, not just NATS reachability
  # [ASSUMPTION: confidence=medium] (ASSUM-012) The healthz endpoint extends the FEAT-FORGE-009 contract — healthy iff the NATS subscription is live AND the orchestrator chain is fully constructed
  @task:TASK-FW10-001
  @integration @edge-case
  Scenario Outline: The healthz probe reflects the orchestrator's readiness state
    Given forge serve is starting up
    When the orchestrator chain is in <chain_state>
    Then the healthz probe should report <health_status>

    Examples:
      | chain_state                                     | health_status |
      | not yet constructed                             | unhealthy     |
      | fully constructed and the consumer is attached  | healthy       |
      | constructed but the NATS subscription dropped   | unhealthy     |
