# Generated by /feature-spec
# Feature: NATS Fleet Integration (FEAT-FORGE-002)
# Stack: python
# Assumptions: 5 (see nats-fleet-integration_assumptions.yaml)
# Generated: 2026-04-24T00:00:00Z

@feat-forge-002 @nats-fleet-integration
Feature: NATS Fleet Integration
  As Rich, the sole operator of Forge
  I want Forge to announce itself on the fleet, track which specialist agents are alive,
    and broadcast every pipeline lifecycle event on the shared bus
  So that Jarvis, dashboards, and downstream notifiers have a reliable live view of Forge,
    and Forge can route work only to specialists that are actually available

  Background:
    Given Forge is configured from the project configuration file
    And the fleet message bus is reachable

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP A — Key Examples
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Core registration — Forge announces itself so other fleet members can discover it
  @task:TASK-NFI-004
  @key-example @smoke
  Scenario: On startup Forge registers itself with the fleet
    When Forge starts
    Then Forge should publish its own capability manifest to the fleet registration channel
    And the fleet registry should list Forge as a ready agent
    And the manifest should include Forge's tools, intents, and trust tier

  # Why: Core heartbeat — liveness signal keeps Forge discoverable
  # [ASSUMPTION: confidence=high] Heartbeat interval is 30 seconds by default (forge.yaml.fleet.heartbeat_interval_seconds)
  @task:TASK-NFI-004
  @key-example @smoke
  Scenario: Forge publishes a heartbeat at the configured interval
    Given Forge has been registered with the fleet
    When the configured heartbeat interval elapses
    Then Forge should publish a heartbeat carrying its current status and workload
    And the heartbeat should reflect whether a build is currently in flight

  # Why: Discovery — keep a live view of which specialists exist
  # [ASSUMPTION: confidence=high] Discovery cache TTL is 30 seconds
  @task:TASK-NFI-003
  @key-example
  Scenario: Forge maintains a live cache of fleet agents
    Given two specialist agents are registered with the fleet
    When Forge is asked to resolve a capability by tool name
    Then Forge should consult its live fleet cache
    And the resolution should identify the matching specialist without re-reading the registry

  # Why: Discovery update — a newly-joined agent becomes visible without restart
  @task:TASK-NFI-005
  @key-example
  Scenario: A newly-registered specialist becomes available for resolution
    Given Forge is watching fleet lifecycle events
    When a new specialist agent publishes its registration
    Then the new agent should be present in Forge's fleet view
    And subsequent resolutions may select the new agent

  # Why: Lifecycle publication — each stage completion is observable on the bus
  @task:TASK-NFI-006
  @key-example @smoke
  Scenario: Forge publishes a stage-complete event after each gated stage
    Given a build is running
    When a pipeline stage completes and is evaluated
    Then Forge should publish a stage-complete event
    And the event should carry the build's correlation identifier
    And the event should describe the stage outcome, the gate decision, and the coach score

  # Why: Lifecycle terminal — a successful build announces completion to downstream listeners
  @task:TASK-NFI-006
  @key-example
  Scenario: Forge publishes a build-complete event when the pipeline finishes successfully
    Given a build has progressed to the finalising stage and produced a pull request
    When the build transitions to complete
    Then Forge should publish a build-complete event carrying the pull request details
    And the event should share the build's originating correlation identifier

  # Why: Graceful shutdown — Forge should remove itself so routing skips it immediately
  @task:TASK-NFI-004
  @key-example
  Scenario: On graceful shutdown Forge deregisters from the fleet
    Given Forge has been registered with the fleet
    When Forge receives a graceful shutdown signal
    Then Forge should publish a deregistration event before exiting
    And the fleet registry should no longer list Forge as an available agent

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP B — Boundary Conditions
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Just-inside boundary — heartbeat age up to the stale threshold is still fresh enough
  # [ASSUMPTION: confidence=high] Stale-heartbeat threshold is 90 seconds (forge.yaml.fleet.stale_heartbeat_seconds)
  @task:TASK-NFI-003
  @boundary @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario Outline: An agent whose last heartbeat is within the stale threshold remains selectable
    Given a specialist agent is registered with the fleet
    And the specialist's most recent heartbeat arrived <seconds_ago> seconds ago
    When Forge is asked to resolve the specialist's tool
    Then the specialist should be considered available

    Examples:
      | seconds_ago |
      | 30          |
      | 60          |
      | 90          |

  # Why: Just-outside boundary — once the stale threshold is crossed, the agent is marked degraded
  @task:TASK-NFI-003
  @boundary @negative @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario: An agent whose last heartbeat is past the stale threshold is excluded from primary resolution
    Given a specialist agent is registered with the fleet
    And the specialist has not sent a heartbeat for longer than the stale-heartbeat threshold
    When Forge is asked to resolve the specialist's tool
    Then the specialist should be marked as degraded in the fleet view
    And the specialist should be excluded from the primary resolution result

  # Why: Just-inside boundary — progress events are emitted at or under the configured interval
  # [ASSUMPTION: confidence=high] Progress cadence is at least every 60 seconds during RUNNING
  @task:TASK-NFI-006
  @boundary @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario: A long-running stage still publishes progress within the configured interval
    Given a build is running a stage that will take several minutes
    When the configured progress interval elapses without a stage transition
    Then Forge should publish a progress event carrying wave and task details
    And the progress event should share the build's correlation identifier

  # Why: Just-inside boundary — intent confidence at the minimum threshold is accepted
  # [ASSUMPTION: confidence=high] Intent-fallback minimum confidence is 0.7
  @task:TASK-NFI-003
  @boundary @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario: Intent-based fallback selects an agent whose confidence is exactly at the minimum threshold
    Given no agent advertises a tool named "draft-plan"
    And one agent advertises an intent whose confidence equals the minimum acceptable confidence
    When Forge is asked to resolve the capability by intent pattern
    Then the agent should be selected as the match

  # Why: Just-outside boundary — intent confidence below the minimum threshold is rejected
  @task:TASK-NFI-003
  @boundary @negative @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario: Intent-based fallback rejects an agent whose confidence is below the minimum threshold
    Given no agent advertises a tool named "draft-plan"
    And the only candidate agent advertises an intent with confidence below the minimum acceptable confidence
    When Forge is asked to resolve the capability by intent pattern
    Then the resolution should return no match

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP C — Negative Cases
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Degraded mode — when no specialist exists, the stage must flag for review, never auto-approve
  @task:TASK-NFI-003
  @negative @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario: Resolving a tool that no fleet agent advertises forces the stage to flag for review
    Given no registered agent advertises the requested tool
    And no registered agent advertises a matching intent
    When the pipeline asks Forge to resolve the capability for a stage
    Then the resolution outcome should be recorded as unresolved
    And the stage should be flagged for human review
    And the stage should not be allowed to auto-approve

  # Why: Degraded mode — an agent marked degraded is not a valid primary match
  @task:TASK-NFI-003
  @negative @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario: A tool advertised only by a degraded agent does not produce a primary match
    Given the only agent advertising the requested tool is currently marked degraded
    When the pipeline asks Forge to resolve the capability
    Then the primary resolution should return no match
    And the stage should be flagged for human review

  # Why: Malformed fleet event — a bad registration must not corrupt the cache
  @task:TASK-NFI-005
  @negative @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario: An invalid registration event is ignored without affecting the live fleet view
    Given Forge is watching fleet registration events
    When a registration event arrives with a payload that fails schema validation
    Then the invalid event should be rejected and logged
    And Forge's fleet view should remain unchanged
    And subsequent valid events should continue to be processed

  # Why: Duplicate registration — re-announcing supersedes, never duplicates
  @task:TASK-NFI-005
  @negative @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario: A repeated registration of the same agent supersedes the prior manifest
    Given an agent is already registered with a known manifest version
    When the same agent re-registers with a newer manifest version
    Then the fleet view should reflect only the newer manifest
    And no duplicate entry should appear for that agent

  # Why: Invalid build trigger — a malformed build-queued payload produces a terminal failure event
  @task:TASK-NFI-007
  @negative @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario: A malformed build-queued payload is acknowledged and reported as failed
    Given Forge is subscribed to the build-queue channel
    When a build-queued message arrives whose payload fails schema validation
    Then the message should be acknowledged so the queue advances
    And Forge should publish a build-failed event explaining the payload was malformed

  # Why: Permission guard — builds whose path is outside the allowlist must not start
  @task:TASK-NFI-007
  @negative @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario: A build whose feature path falls outside the configured allowlist is refused
    Given the configuration specifies an allowlist of permitted paths
    When a build-queued message arrives with a feature path outside that allowlist
    Then the build should not start
    And Forge should publish a build-failed event explaining the path is not permitted

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP D — Edge Cases
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Cache freshness — stale cache triggers a live registry re-read before resolution
  @task:TASK-NFI-003
  @edge-case @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario: A resolution after the cache has gone stale re-reads the fleet registry
    Given Forge has a cached fleet view older than the cache freshness window
    When Forge is asked to resolve a capability
    Then the fleet registry should be re-read before the resolution is produced
    And the resolution should be made against the refreshed view

  # Why: Two equally-qualified agents — tie-break preserves a deterministic ordering
  @task:TASK-NFI-003
  @edge-case @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario: When two agents advertise the same tool, the higher trust tier is preferred
    Given two registered agents both advertise the requested tool
    And one agent's trust tier ranks above the other
    When Forge is asked to resolve the tool
    Then the higher-ranked agent should be selected
    And the other agent should be recorded as a competing candidate

  # Why: Two equally-qualified agents at the same tier — queue depth tie-breaks
  @task:TASK-NFI-003
  @edge-case @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario: When two agents at the same trust tier advertise the same tool, the one with the shallower queue is preferred
    Given two registered agents at the same trust tier both advertise the requested tool
    And the most recent heartbeats report different queue depths
    When Forge is asked to resolve the tool
    Then the agent with the shallower queue should be selected

  # Why: Lifecycle event for a paused stage — downstream listeners get informed immediately
  @task:TASK-NFI-008
  @edge-case @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario: Flagging a stage for human review publishes a build-paused event
    Given a build is running and a gate decision flags the current stage for review
    When the pipeline prepares to wait for a decision
    Then Forge should publish a build-paused event before entering the paused state
    And the paused event should carry the rationale and the reply subject for a decision

  # Why: Resume after approval — the lifecycle event carries the decision that unblocked the build
  @task:TASK-NFI-006
  @edge-case @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario: Resuming a paused build publishes a build-resumed event
    Given a build is paused waiting for a decision
    When an approval response rehydrates the build
    Then Forge should publish a build-resumed event
    And the event should carry the decision and the responder

  # Why: Crash recovery — a paused build in history is re-announced so listeners don't miss it
  @task:TASK-NFI-009
  @edge-case @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario: Restarting Forge with a paused build in the history re-emits the paused event
    Given Forge's history records a paused build awaiting a decision
    When Forge restarts and reconciles its state
    Then Forge should re-publish a build-paused event for that build
    And the event should carry the original build's correlation identifier

  # Why: Correlation threading — every lifecycle event for a build carries the original correlation id
  @task:TASK-NFI-008
  @edge-case @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario: All lifecycle events for one build share the originating correlation identifier
    Given a build has been queued with a known correlation identifier
    When Forge publishes started, progress, stage-complete, and complete events for that build
    Then every published event should carry the same originating correlation identifier

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP E — Security, Concurrency, Data Integrity, Integration Boundaries
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Secrets must never leak onto the bus via manifests
  @task:TASK-NFI-002
  @edge-case @security @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario: Forge's registration manifest excludes runtime secrets
    When Forge publishes its capability manifest to the fleet
    Then the manifest should not contain any API keys, credentials, or connection strings
    And the manifest should only describe capabilities, identity, and permissions

  # Why: Trigger authenticity — builds may only be initiated by approved originators
  @task:TASK-NFI-007
  @edge-case @security @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario: A build-queued message from an unrecognised originating adapter is refused
    Given Forge is subscribed to the build-queue channel
    When a build-queued message arrives declaring an originating adapter that is not on the approved list
    Then the build should not start
    And Forge should publish a build-failed event explaining the originator was not recognised

  # Why: Concurrent fleet updates — the cache must remain consistent under racing events
  @task:TASK-NFI-005
  @edge-case @concurrency @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario: Simultaneous fleet-change events update the cache without loss
    Given two agents publish registration and deregistration events at effectively the same moment
    When Forge processes both events
    Then the final fleet view should reflect each event exactly once
    And neither update should overwrite the other's effect

  # Why: Acknowledgement is terminal — a completed build must not be re-picked from the queue
  @task:TASK-NFI-007
  @edge-case @concurrency @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario: A build-queued message is not redelivered after terminal acknowledgement
    Given a build has reached a terminal outcome and has been acknowledged on the queue
    When the build-queue is inspected
    Then no redelivery of that build should occur
    And the queue should advance to the next pending item

  # Why: History is the source of truth — transport failures don't rewrite recorded progress
  @task:TASK-NFI-006
  @edge-case @data-integrity @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario: A lifecycle publish failure does not roll back the build's recorded progress
    Given a build has just transitioned to the running state and been recorded in history
    When publishing the build-started event fails at the transport layer
    Then the build should remain recorded as running in the local history
    And the failure should be logged for later reconciliation
    And the build should continue without aborting

  # Why: At-least-once delivery — redelivery must not restart a completed build
  @task:TASK-NFI-009
  @edge-case @data-integrity @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario: A redelivered build-queued message for a completed build is acknowledged idempotently
    Given a build is already recorded as complete in the local history
    When the build-queue redelivers the original build-queued message after a restart
    Then Forge should acknowledge the redelivery without starting a new build
    And no duplicate build record should be created

  # Why: Liveness must survive transient registry problems — heartbeats are independent
  @task:TASK-NFI-004
  @edge-case @integration @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario: Heartbeats continue to publish even when the fleet registry is temporarily unreachable
    Given Forge has been registered with the fleet
    When the fleet registry becomes temporarily unreachable while the bus remains up
    Then Forge should continue publishing heartbeats at the configured interval
    And Forge should attempt to refresh its fleet view when the registry becomes reachable again

  # Why: Paused builds hold their place in the queue — the message stays unacked until terminal
  @task:TASK-NFI-007
  @edge-case @integration @skip
  # SKIP: pending step-function implementation — tracked by TASK-NFI-011 follow-up.
  Scenario: A paused build holds its queue position until a terminal decision is reached
    Given a build is paused waiting for a decision
    When Forge is asked whether the underlying queue message has been acknowledged
    Then the message should remain unacknowledged
    And the queue should not advance to the next pending item until the paused build reaches a terminal state
