# Generated by /feature-spec
# Feature: GuardKit Command Invocation Engine (FEAT-FORGE-005)
# Stack: python
# Assumptions: 7 (see guardkit-command-invocation-engine_assumptions.yaml)
# Generated: 2026-04-24T00:00:00Z

@feat-forge-005 @guardkit-invocation-engine
Feature: GuardKit Command Invocation Engine
  As Rich, the sole operator of Forge
  I want Forge to invoke GuardKit subcommands as subprocesses with context flags assembled automatically,
    stream progress while running, capture artefacts, and handle failures without crashing the build,
  So that the pipeline can drive /system-arch, /feature-spec, /feature-plan, autobuild, and related
    GuardKit commands end-to-end without hand-assembled flags or brittle output parsing.

  Background:
    Given Forge is running inside an ephemeral build worktree
    And a project configuration file defines the shell, filesystem, and network permissions
    And a context manifest is available at the repo root describing documents grouped by category

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP A — Key Examples
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Core invocation — a GuardKit subcommand runs and returns a parsed success result
  @task:TASK-GCI-008
  @key-example @smoke
  Scenario: A GuardKit subcommand completes successfully and its artefacts are captured
    Given the reasoning model invokes a GuardKit subcommand wrapper for the current build
    When the GuardKit process exits cleanly
    Then the invocation should report success
    And the returned result should list every artefact path emitted by GuardKit
    And the returned result should include the command's wall-clock duration
    And the returned result should include the Coach score when GuardKit produced one

  # Why: Auto-assembled context flags — the central value prop, zero hand-wiring
  # [ASSUMPTION: confidence=high] /feature-spec pulls manifest categories: specs, contracts, source, decisions
  @task:TASK-GCI-003
  @key-example @smoke
  Scenario: Context flags are assembled automatically from the manifest for the invoked subcommand
    Given the manifest lists documents tagged with multiple categories
    When Forge invokes the feature-spec wrapper
    Then the resolver should select only documents whose category is relevant to feature-spec
    And every always-included document should be prepended to the context list
    And the subprocess command line should carry one context flag per selected document

  # Why: Live telemetry — progress events surface on the bus while the subprocess still runs
  @task:TASK-GCI-005
  @key-example
  Scenario: GuardKit progress is streamed on the bus while the subprocess is still running
    Given the reasoning model invokes any GuardKit wrapper that supports streaming
    When the GuardKit process emits progress events during its run
    Then Forge should observe each progress event on the pipeline progress channel
    And the blocking invocation should still return only after the subprocess exits

  # Why: Error contract — the tool layer must never raise past its boundary
  @task:TASK-GCI-004
  @key-example @smoke
  Scenario: A failing GuardKit subprocess is reported as a structured error, not an exception
    Given the reasoning model invokes a GuardKit wrapper
    When the subprocess exits with a non-zero status
    Then the invocation should return a structured failure result
    And the failure result should carry the captured error output
    And the tool layer should not propagate an exception to the reasoning model

  # Why: Worktree confinement — every subprocess runs inside the build's ephemeral directory
  @task:TASK-GCI-008
  @key-example
  Scenario: Subprocesses are executed inside the current build's worktree
    Given a build's worktree has been prepared
    When any GuardKit, git, or shell subprocess is launched through the adapter
    Then the subprocess working directory should be the build's worktree
    And the subprocess should not be able to read or write outside the allowed worktree paths

  # Why: Version control adapter — PR creation is the terminal artefact of a build
  @task:TASK-GCI-007
  @key-example
  Scenario: Forge opens a pull request for the build through the version-control adapter
    Given a build has committed and pushed its work to a remote branch
    When Forge asks the version-control adapter to open a pull request
    Then the adapter should create the pull request against the configured base branch
    And the invocation should return the pull-request URL as a structured result

  # Why: Graphiti subcommands bypass manifest resolution — they don't take --context
  @task:TASK-GCI-010
  @key-example
  Scenario: Graphiti GuardKit subcommands skip context-manifest resolution entirely
    When Forge invokes a Graphiti GuardKit wrapper
    Then no context flags should be assembled
    And no manifest lookup should be performed for this invocation

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP B — Boundary Conditions
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Just-inside timeout — a subprocess that finishes just before the cap still succeeds
  # [ASSUMPTION: confidence=high] Default subprocess timeout is 600 seconds
  @task:TASK-GCI-008
  @boundary
  Scenario Outline: A subprocess that finishes within the timeout is reported as successful
    Given the subprocess timeout has been configured
    When a GuardKit wrapper completes after <seconds> seconds of runtime
    Then the invocation should report success
    And the returned duration should match the observed runtime

    Examples:
      | seconds |
      | 1       |
      | 300     |
      | 599     |

  # Why: Just-outside timeout — once the cap is breached, the result is "timeout", not "failed"
  @task:TASK-GCI-008
  @boundary @negative
  Scenario: A subprocess that exceeds the timeout is reported as timed-out
    Given the subprocess timeout has been configured
    When a GuardKit wrapper has been running longer than the configured timeout
    Then the invocation should return a timeout result
    And the reasoning model should be free to decide whether to retry or escalate

  # Why: Depth-2 dependency chase — the resolver should follow one hop into a sibling repo
  # [ASSUMPTION: confidence=high] Dependency traversal depth cap is 2
  @task:TASK-GCI-003
  @boundary
  Scenario: Context resolution follows dependency references up to the depth cap
    Given the manifest declares a dependency on a sibling repository
    And the sibling repository declares its own manifest with key documents
    When Forge invokes a subcommand that consumes both manifests' categories
    Then the resolver should include selected documents from both manifests
    And the final context list should preserve a stable order

  # Why: Just-outside depth — traversing a deeper chain should stop and warn, not explode
  @task:TASK-GCI-003
  @boundary @edge-case
  Scenario: Context resolution stops at the depth cap and warns instead of recursing further
    Given the manifest chain would require traversing beyond the resolver's depth cap
    When Forge resolves context flags for a subcommand
    Then the resolver should stop at the depth cap
    And the resolver should emit a structured cycle-detected warning
    And the invocation should still proceed with the documents resolved so far

  # Why: Just-inside stdout-tail — a compact stdout is preserved verbatim
  # [ASSUMPTION: confidence=high] stdout_tail captures the last 4 KB of subprocess output
  @task:TASK-GCI-004
  @boundary
  Scenario: A compact stdout is preserved verbatim in the returned result
    Given a GuardKit subprocess that prints fewer than four kilobytes to standard output
    When the invocation completes
    Then the returned result should include the full standard output

  # Why: Just-outside stdout-tail — larger output is truncated to the tail, not dropped
  @task:TASK-GCI-004
  @boundary
  Scenario: A large stdout is truncated to the most recent tail in the returned result
    Given a GuardKit subprocess that prints far more than the captured tail size
    When the invocation completes
    Then the returned result should include only the most recent slice of standard output
    And the slice size should match the configured tail limit

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP C — Negative Cases
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Missing manifest — proceed without --context rather than blocking adoption
  @task:TASK-GCI-003
  @negative
  Scenario: A missing context manifest degrades gracefully to no context flags
    Given the target repository has no context manifest
    When Forge invokes any GuardKit wrapper for that repository
    Then the invocation should proceed with no context flags
    And a structured warning should be recorded indicating the manifest was missing
    And the reasoning model should be able to see the warning in the returned result

  # Why: A binary that isn't on the allowlist must be refused before it runs
  @task:TASK-GCI-008
  @negative
  Scenario: A subprocess whose binary is not in the shell allowlist is refused
    Given the project configuration lists the permitted shell binaries
    When the reasoning model attempts to execute a binary that is not on the allowlist
    Then the subprocess should be refused before launch
    And the invocation should return a structured permissions error
    And no side effects should occur on the worktree

  # Why: A cwd outside the worktree allowlist must be refused — worktree confinement invariant
  @task:TASK-GCI-008
  @negative
  Scenario: A subprocess targeting a working directory outside the allowlist is refused
    Given the project configuration allows subprocesses only within the build worktrees path
    When a subprocess is requested with a working directory outside that path
    Then the subprocess should be refused before launch
    And the invocation should return a structured permissions error

  # Why: Non-zero exit with captured stderr — must reach the reasoning model intact
  @task:TASK-GCI-004
  @negative
  Scenario: A non-zero exit is reported as a failure with the subprocess error output
    Given the reasoning model invokes a GuardKit wrapper
    When the subprocess exits with a non-zero status and writes diagnostics to its error stream
    Then the invocation should return a structured failure result
    And the failure result should include the subprocess exit status and error output

  # Why: Tolerant parser — unknown output shape should NOT explode the whole call
  @task:TASK-GCI-004
  @negative @edge-case
  Scenario: An unknown GuardKit output shape degrades to success with no artefacts
    Given the reasoning model invokes a GuardKit wrapper
    When the subprocess exits cleanly but its output does not match the expected artefact shape
    Then the invocation should still report success
    And the returned artefact list should be empty
    And the reasoning model should be responsible for deciding whether the stage produced useful work

  # Why: Documents outside the filesystem read-allowlist must be omitted, not silently included
  @task:TASK-GCI-003
  @negative
  Scenario: Context documents that fall outside the read allowlist are omitted with a warning
    Given the manifest references a document whose path is outside the filesystem read allowlist
    When Forge resolves context flags for a subcommand
    Then the out-of-allowlist document should be omitted from the context list
    And a structured warning should be emitted identifying the omitted document

  # Why: Missing GitHub credentials — surface at the adapter boundary, never raise
  @task:TASK-GCI-007
  @negative
  Scenario: A pull-request creation without GitHub credentials returns a structured error
    Given the runtime has no GitHub access credentials available
    When Forge asks the version-control adapter to open a pull request
    Then the adapter should return a structured error explaining the credential is missing
    And no pull request should be created

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP D — Edge Cases
  # ─────────────────────────────────────────────────────────────────────────

  # Why: The resolver must not loop on a circular dependency graph
  @task:TASK-GCI-003
  @edge-case
  Scenario: A circular dependency chain is detected and resolved safely
    Given two repositories' manifests reference one another as dependencies
    When Forge resolves context flags for a subcommand
    Then the resolver should detect the cycle before repeating a manifest
    And the resolver should stop at the depth cap
    And a structured cycle-detected warning should be recorded

  # Why: Worktree cleanup is best-effort — must not block terminal transitions
  @task:TASK-GCI-006
  @edge-case
  Scenario: A failed worktree cleanup is logged but does not prevent build completion
    Given a build has reached a terminal state
    When the adapter attempts to delete the build's worktree
    And the deletion fails
    Then the build should still be marked as terminal in history
    And a structured warning should be logged about the failed cleanup

  # Why: NATS progress stream is telemetry, not authoritative — outcome must still be returned
  @task:TASK-GCI-005
  @edge-case
  Scenario: The authoritative result still returns when progress streaming is unavailable
    Given the progress stream channel is unavailable during a GuardKit invocation
    When the subprocess exits cleanly
    Then the invocation should still return a parsed success result with artefact paths
    And the missing progress stream should not itself fail the call

  # Why: Retry with additional context — explicit build-plan requirement ("error handling and retry")
  # [ASSUMPTION: confidence=medium] A failed invocation can be retried with extra context flags chosen by the reasoning model
  @task:TASK-GCI-008
  @edge-case
  Scenario: A failed invocation can be retried with additional explicit context
    Given a GuardKit wrapper has returned a failure result
    When the reasoning model retries the same wrapper with additional explicit context paths
    Then the retry should merge the explicit paths with the manifest-derived ones
    And the retry should be a fresh subprocess launch, not a continuation

  # Why: Tool-layer exceptions must never escape — the universal error contract
  @task:TASK-GCI-009
  @edge-case
  Scenario: An unexpected error inside a wrapper is returned as a structured error, not raised
    Given any GuardKit wrapper is invoked
    When an unexpected internal error occurs inside the wrapper
    Then the wrapper should catch the error
    And the wrapper should return a structured error result describing the error type and message
    And no exception should propagate to the reasoning model

  # Why: Multiple parallel invocations within the same build — important for autobuild fan-out
  # [ASSUMPTION: confidence=medium] Multiple GuardKit wrappers may run in parallel within the same build worktree
  @task:TASK-GCI-008
  @edge-case
  Scenario: Parallel GuardKit invocations in the same build do not corrupt each other's results
    Given two GuardKit wrappers are invoked in parallel within the same build
    When both subprocesses complete
    Then each invocation should receive its own independent structured result
    And neither result should contain artefacts or progress events belonging to the other

  # ─────────────────────────────────────────────────────────────────────────
  # GROUP E — Security, Concurrency, and Integration Boundaries
  # ─────────────────────────────────────────────────────────────────────────

  # Why: Path traversal in a manifest entry must not escape the repository root
  @task:TASK-GCI-003
  @edge-case @negative
  Scenario: A context manifest entry that would escape the repository root is rejected
    Given the context manifest lists a document path that resolves outside the target repository
    When Forge resolves context flags for a subcommand
    Then the out-of-repository path should be omitted from the context list
    And a structured warning should be emitted identifying the rejected path
    And the invocation should proceed with the remaining valid documents

  # Why: Shell-metacharacter injection via arguments must stay literal, not expand
  @task:TASK-GCI-006
  @edge-case @negative
  Scenario: Shell metacharacters in subprocess arguments are passed as literal tokens
    Given the reasoning model builds subprocess arguments that contain shell metacharacters
    When the adapter launches the subprocess
    Then each argument should be delivered to the binary as a single literal token
    And no shell expansion or secondary command should be evaluated

  # Why: Two concurrent builds targeting the same repo must resolve independently
  # [ASSUMPTION: confidence=medium] Context resolution has no cached state shared across concurrent builds
  @task:TASK-GCI-003
  @edge-case
  Scenario: Two concurrent builds against the same repository resolve context independently
    Given two builds are running at the same time against the same target repository
    When each build invokes a GuardKit wrapper requiring context resolution
    Then each build should receive its own resolved context flag list
    And one build's resolver warnings should not appear in the other build's result

  # Why: Cancellation must terminate in-flight subprocess and discard partial artefacts
  @task:TASK-GCI-008
  @edge-case
  Scenario: A cancelled build terminates its in-flight subprocess cleanly
    Given a GuardKit subprocess is currently running inside a build
    When the build is cancelled
    Then the subprocess should be terminated
    And any partial artefacts produced by the terminated subprocess should not be reported as completed work

  # Why: The live status view must not miss progress events because of slow consumption
  @task:TASK-GCI-005
  @edge-case
  Scenario: Progress events emitted faster than Forge consumes them are still observable for live status
    Given a GuardKit subprocess is emitting progress events at a high cadence
    When Forge is slower to consume than the producer is to emit
    Then the live status view should still reflect the most recent progress events
    And the authoritative completion result should remain unaffected

  # Why: A stalled subprocess with no output still hits the timeout, never hangs the build
  @task:TASK-GCI-008
  @edge-case
  Scenario: A silent stalled subprocess is terminated by the configured timeout
    Given a GuardKit subprocess has produced no standard output and no progress events
    When the subprocess has been running longer than the configured timeout
    Then the invocation should return a timeout result
    And the subprocess should be terminated before its process handle is released
