"""Pure-domain data models for the Forge discovery layer.

This module exports two pydantic models used by the discovery domain:

* :class:`DiscoveryCacheEntry` — in-memory cache record combining an
  :class:`~nats_core.manifest.AgentManifest` with the latest heartbeat
  snapshot. Never persisted; lives only in :class:`forge.discovery.cache.DiscoveryCache`.
* :class:`CapabilityResolution` — the output of
  :func:`forge.discovery.resolve.resolve`, destined for Graphiti
  write-back via a later feature (see DM-discovery §5).

The module is **pure domain**: no NATS imports, no transport concerns.
``AgentManifest`` is imported only because it is the published schema
type — the discovery layer never speaks to NATS itself.

See ``docs/design/models/DM-discovery.md`` §2 for the canonical schema.
"""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from nats_core.manifest import AgentManifest
from pydantic import BaseModel, ConfigDict, Field, model_validator

# Heartbeat status values are a superset of AgentManifest.status — they
# include "busy" and "draining" which only appear at runtime via heartbeats.
HeartbeatStatus = Literal["ready", "busy", "degraded", "draining"]

# Match-source values mirror DM-discovery §3 — exactly three states.
MatchSource = Literal["tool_exact", "intent_pattern", "unresolved"]

# Trust-tier ordering: core(0) > specialist(1) > extension(2).
TrustTier = Literal["core", "specialist", "extension"]


class DiscoveryCacheEntry(BaseModel):
    """In-memory cache record for one fleet agent.

    Attributes:
        manifest: The agent's :class:`AgentManifest` from the
            ``agent-registry`` KV bucket.
        last_heartbeat_at: UTC timestamp of the most recent heartbeat
            received for this agent.
        last_heartbeat_status: Status from the most recent heartbeat —
            one of ``ready | busy | degraded | draining``.
        last_queue_depth: Latest queue depth reported by the agent.
        last_active_tasks: Latest active-task count reported by the agent.
        cached_at: UTC timestamp the entry was inserted/last refreshed.
            Used for TTL evaluation by ``ensure_cache_fresh``.
    """

    model_config = ConfigDict(extra="forbid")

    manifest: AgentManifest = Field(description="Published agent manifest snapshot")
    last_heartbeat_at: datetime = Field(
        description="UTC timestamp of the most recent heartbeat",
    )
    last_heartbeat_status: HeartbeatStatus = Field(
        description="Status from the most recent heartbeat",
    )
    last_queue_depth: int = Field(
        default=0,
        ge=0,
        description="Latest queue depth reported by the agent",
    )
    last_active_tasks: int = Field(
        default=0,
        ge=0,
        description="Latest active-task count reported by the agent",
    )
    cached_at: datetime = Field(
        description="UTC timestamp the entry was inserted/last refreshed",
    )


class CapabilityResolution(BaseModel):
    """Result of one ``resolve()`` call. One per dispatch attempt.

    Persists to ``forge_pipeline_history`` via Graphiti (covered by a
    later feature — *not* this task).

    Invariant: ``matched_agent_id is None`` iff
    ``match_source == "unresolved"`` (DM-discovery §7).

    Attributes:
        resolution_id: UUID generated by the caller. The discovery layer
            never invents IDs — the caller (dispatch tool) owns identity.
        build_id: Pipeline build identifier this resolution belongs to.
        stage_label: Stage within the build that triggered the dispatch.
        requested_tool: Tool name the caller is dispatching against.
        requested_intent: Optional intent pattern for fallback matching.
        matched_agent_id: Chosen agent's ``agent_id``, or ``None`` when
            ``match_source == "unresolved"``.
        match_source: How the match was made — exact tool, intent
            fallback, or unresolved.
        competing_agents: Other agents that also matched but lost the
            tie-break. Excludes the chosen agent (DM-discovery §7).
        chosen_trust_tier: Trust tier of the chosen agent, or ``None``
            for unresolved.
        chosen_confidence: For ``intent_pattern`` matches, the matched
            ``IntentCapability.confidence``. For ``tool_exact``, ``1.0``.
            ``None`` for unresolved.
        chosen_queue_depth: Queue depth from the chosen agent's latest
            heartbeat. ``None`` for unresolved.
        resolved_at: UTC timestamp the resolution completed.
        outcome_correlated: ``True`` once the downstream
            :class:`~nats_core.events.ResultPayload` is linked back via
            :func:`correlate_outcome`. Append-only — cannot regress.
    """

    model_config = ConfigDict(extra="forbid")

    resolution_id: str = Field(min_length=1, description="UUID for this resolution")
    build_id: str = Field(min_length=1, description="Pipeline build identifier")
    stage_label: str = Field(min_length=1, description="Stage within the build")

    requested_tool: str = Field(min_length=1, description="Tool name requested")
    requested_intent: str | None = Field(
        default=None, description="Intent pattern requested (fallback path)",
    )

    matched_agent_id: str | None = Field(
        default=None, description="Chosen agent_id, or None when unresolved",
    )
    match_source: MatchSource = Field(description="How the match was made")
    competing_agents: list[str] = Field(
        default_factory=list,
        description="Other agents that matched but lost the tie-break",
    )

    chosen_trust_tier: TrustTier | None = Field(
        default=None, description="Trust tier of the chosen agent",
    )
    chosen_confidence: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        description="Confidence score of the matched capability",
    )
    chosen_queue_depth: int | None = Field(
        default=None, ge=0, description="Queue depth of the chosen agent",
    )

    resolved_at: datetime = Field(description="UTC timestamp the resolution completed")
    outcome_correlated: bool = Field(
        default=False,
        description="True once the ResultPayload has been linked back",
    )

    @model_validator(mode="after")
    def _check_unresolved_invariant(self) -> CapabilityResolution:
        """Enforce DM-discovery §7: matched_agent_id ⇔ match_source.

        Raises:
            ValueError: If ``matched_agent_id`` and ``match_source`` are
                inconsistent — e.g. ``unresolved`` with a non-None agent
                or a real match-source with a ``None`` agent.
        """
        unresolved = self.match_source == "unresolved"
        has_agent = self.matched_agent_id is not None
        if unresolved and has_agent:
            raise ValueError(
                "match_source='unresolved' requires matched_agent_id=None",
            )
        if not unresolved and not has_agent:
            raise ValueError(
                f"match_source={self.match_source!r} requires matched_agent_id",
            )
        # competing_agents must not include the chosen agent.
        if has_agent and self.matched_agent_id in self.competing_agents:
            raise ValueError(
                "competing_agents must not include matched_agent_id",
            )
        return self


__all__ = [
    "CapabilityResolution",
    "DiscoveryCacheEntry",
    "HeartbeatStatus",
    "MatchSource",
    "TrustTier",
]
